#!/bin/bash

install-go() {
	curl https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz -o /tmp/go1.13.5.linux-amd64.tar.gz
	sudo tar -C /usr/local -xzvf ./tmp/go
}

install-powerline-go() {
	go get -u github.com/justjanne/powerline-go
}

export GOARCH=amd64
export GOOS=linux
export GOPATH="$HOME"/.go
export PATH=$PATH:/usr/local/go/bin:"$GOPATH"/bin


function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go -error $?)"
}
if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
