#!/bin/bash
#
export PYTHON_VERSION="python3.8"
export POWERLINE_BINDINGS="$HOME/.local/lib/$PYTHON_VERSION/site-packages/powerline/bindings/bash/powerline.sh"

powerline-daemon -q
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
bash "$POWERLINE_BINDINGS"
# . /usr/share/powerline/bindings/bash/powerline.sh
