#!/bin/bash
#
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. .local/lib/python3.6/site-packages/powerline/bindings/bash/powerline.sh
# . /usr/share/powerline/bindings/bash/powerline.sh
