var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,e,f){if(null==a)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,f){a!=Array.prototype&&a!=Object.prototype&&(a[e]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,f,n){if(e){f=$jscomp.global;a=a.split(".");for(n=0;n<a.length-1;n++){var q=a[n];q in f||(f[q]={});f=f[q]}a=a[a.length-1];n=f[a];e=e(n);e!=n&&null!=e&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,f){var e=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var q=e.length,p=a.length;f=Math.max(0,Math.min(f|0,e.length));for(var k=0;k<p&&f<q;)if(e[f++]!=a[k++])return!1;return k>=p}},"es6","es3");$jscomp.findInternal=function(a,e,f){a instanceof String&&(a=String(a));for(var n=a.length,q=0;q<n;q++){var p=a[q];if(e.call(f,p,q,a))return{i:q,v:p}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6","es3");$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,f){var e=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===f&&(f=e.length);f=Math.max(0,Math.min(f|0,e.length));for(var q=a.length;0<q&&0<f;)if(e[--f]!=a[--q])return!1;return 0>=q}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,e){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,n={next:function(){if(f<a.length){var q=f++;return{value:e(q,a[q]),done:!1}}n.next=function(){return{done:!0,value:void 0}};return n.next()}};n[Symbol.iterator]=function(){return n};return n};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");var MessageCommand={OpenLibrary:1,Highlight:2,NextPage:3,Alert:4,Confirm:5,Style:6,Read:7,Stop:8,UpdateReadingStatus:9},RequestCommand={GetSettings:1,GetTemplate:2,GetBookStatus:3,SetSettings:4,SetBookPos:5,Play:6,Stop:7,Speak:8,ReportIssue:9},IssueType={None:0,Missing:1,Wrong:2,Others:4,Title:16,Author:32,Time:64,Body:128,Language:256};var Consts={DefaultUsername:"",SiteExpireInSeconds:604800,TtsEvents:{started:"started",ended:"ended",paused:"paused",resumed:"resumed",data:"data",block:"block",status:"status",error:"error"},TtsCommands:{stop:"stop",play:"play",resume:"resume",pause:"pause",prev:"prev",next:"next",first:"first",last:"last",voice:"voice",seletcion:"selection",paragraph:"paragraph",article:"article"},AbbrWords:{"u.s.":!0,"a.":!0,"n.":!0,"sen.":!0,"dr.":!0,"esq.":!0,"jon.":!0,"jr.":!0,"mr.":!0,"mrs.":!0,"ms.":!0,"messrs.":!0,
"mmes.":!0,"msgr.":!0,"prof.":!0,"rev.":!0,"rt.":!0,"sr.":!0,"st.":!0,"jan.":!0,"feb.":!0,"mar.":!0,"apr.":!0,"may.":!0,"jun.":!0,"jul.":!0,"aug.":!0,"spt.":!0,"oct.":!0,"nov.":!0,"dec.":!0,"co.":!0,"a.m.":!0,"p.m.":!0,"i.e.":!0,"no.":!0,"e.g.":!0,"etc.":!0},StopWords:{and:!0,to:!0,a:!0,of:!0,"for":!0,as:!0,i:!0,"with":!0,until:!0,is:!0,on:!0,that:!0,"this":!0,can:!0,"in":!0,be:!0,has:!0,"if":!0},HeadTags:{title:!0,script:!0,meta:!0,link:!0},ArticleNames:"article content container page main story".split(" "),
AttrTags:["id","class","itemprop","rel"],TitleTags:["Title","title"],AuthorTags:["[rel='author']","[itemprop='author']",".article-metabar-author",".asset-metabar-author"],TimeTags:["time:first",".date:first",".timestamp:first",".article-meta-date:first",".asset-metabar-time:first"],AuthorWildTags:"author_name author-name Author author Byline byline createdby".split(" "),TimeWildTags:"Time Date time date timestamp Timestamp Published published pub-date post-date posted Updated updated".split(" "),
MetaTimeTags:["meta[property='article:published_time']","meta[itemprop='datePublished']","meta[name='article:published_time']","meta[name='publishdate']"],BodyTags:"article entry body main content post container story page entry text".split(" "),CommonNodeNames:["div","span"],SpecialNodeNames:"article section time dd h1 h2 h3".split(" "),ScribdHost:"scribd.com",RsaPublicKey:"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6/cFc8xp/shUJy131ml\nI2URZT82B5wpjj2CESHqCMUujASIyNwNJ1AJuJ54SGidxMMoWh3q0u+6apKEDKDA\nUAEIMDlbKvtKDLpv+gKeGxSwb+16pEawaRkFca1RuP4zCsRJJnKXZwHg9mFz/jxW\nPznsmPMJ30Blc0ie40pA1VJm9qGcaUjDQrFwSUqyapoXpOOdO7cQXj3cYwS+ovsz\nkz7g1NfrgKapp81MJnO/gzEmfJenOxokUmDmzaegcTej4Ymd/MIyR0BjCakWlZbl\nm6lXIj1JBDPploKIC0rrX7O8ROeTJuJb/eQpZGKJIZdxHM23lZnkIYisD9EKLdw6\n8QIDAQAB\n-----END PUBLIC KEY-----"},
ErrorCode={None:0,NoTemplate:1,NoText:2,NoDocument:3,ParseArticleError:4,SystemError:500,ErrorMissingAPIKey:8001,ErrorInvalidAPIKey:8002,ErrorMissingAPIUser:8003,ErrorLicenseTokenRequired:8004,ErrorLicenseExpired:8005,ErrorLicenseNone:8006,ErrorLicenseTokenExpired:8007},ReadTypes={Selection:0,Paragraph:1,Article:2},ShortcutCommands={Read:"read",Stop:"Stop"},TranslationPopupKey={None:"None",Ctrl:"Ctrl",Alt:"Alt",Shift:"Shift"},ThemeBackgroundColors={"black-tie":"#ffeb80",blitzer:"#fbf8ee",cupertino:"#ffef8f",
"dark-hive":"#eeeeee","dot-luv":"#0b58a2",eggplant:"#fafafa","excite-bike":"#c5ddfc",flick:"#ffffff","hot-sneaks":"#ffff38",humanity:"#f5f5b5","le-frog":"#fbf5d0","mint-choc":"#619226",overcast:"#eeeeee","pepper-grinder":"#f7f3de",redmond:"#fbec88",smoothness:"#fbf9ee","south-street":"#fcf0ba",start:"#f8da4e",sunny:"#fff9e5","swanky-purse":"#d5ac5d",trontastic:"#f1fbe5","ui-darkness":"#eeeeee","ui-lightness":"#ffe45c",vader:"#555555"};function Langs$(){}
Langs$.prototype=function(){var a=[],e={ab:{name:"Abkhazian","native":"\u0430\u04a7\u0441\u0448\u04d9\u0430"},aa:{name:"Afar","native":"Afaraf"},af:{name:"Afrikaans","native":"Afrikaans"},ak:{name:"Akan","native":"Akan"},sq:{name:"Albanian","native":"Shqip"},am:{name:"Amharic","native":"\u12a0\u121b\u122d\u129b"},ar:{name:"Arabic","native":"\u0627\u0644\u0639\u0631\u0628\u064a\u0629"},an:{name:"Aragonese","native":"aragon\u00e9s"},hy:{name:"Armenian","native":"\u0540\u0561\u0575\u0565\u0580\u0565\u0576"},as:{name:"Assamese",
"native":"\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be"},av:{name:"Avaric","native":"\u0430\u0432\u0430\u0440 \u043c\u0430\u0446\u04c0"},ae:{name:"Avestan","native":"avesta"},ay:{name:"Aymara","native":"aymar aru"},az:{name:"Azerbaijani","native":"az\u0259rbaycan dili"},bm:{name:"Bambara","native":"bamanankan"},ba:{name:"Bashkir","native":"\u0431\u0430\u0448\u04a1\u043e\u0440\u0442"},eu:{name:"Basque","native":"euskara"},be:{name:"Belarusian","native":"\u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f \u043c\u043e\u0432\u0430"},
bn:{name:"Bengali","native":"\u09ac\u09be\u0982\u09b2\u09be"},bh:{name:"Bihari languages","native":"\u092d\u094b\u091c\u092a\u0941\u0930\u0940"},bi:{name:"Bislama","native":"Bislama"},bs:{name:"Bosnian","native":"bosanski jezik"},br:{name:"Breton","native":"brezhoneg"},bg:{name:"Bulgarian","native":"\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a"},my:{name:"Burmese","native":"\u1017\u1019\u102c\u1005\u102c"},ca:{name:"Catalan, Valencian","native":"catal\u00e0"},ch:{name:"Chamorro",
"native":"Chamoru"},ce:{name:"Chechen","native":"\u043d\u043e\u0445\u0447\u0438\u0439\u043d \u043c\u043e\u0442\u0442"},ny:{name:"Chichewa, Chewa, Nyanja","native":"chiChe\u0175a"},zh:{name:"Chinese","native":"\u4e2d\u6587"},cv:{name:"Chuvash","native":"\u0447\u04d1\u0432\u0430\u0448 \u0447\u04d7\u043b\u0445\u0438"},kw:{name:"Cornish","native":"Kernewek"},co:{name:"Corsican","native":"corsu"},cr:{name:"Cree","native":"\u14c0\u1426\u1403\u152d\u140d\u140f\u1423"},hr:{name:"Croatian","native":"hrvatski jezik"},
cs:{name:"Czech","native":"\u010de\u0161tina"},da:{name:"Danish","native":"dansk"},dv:{name:"Divehi, Dhivehi, Maldivian","native":"\u078b\u07a8\u0788\u07ac\u0780\u07a8"},nl:{name:"Dutch, Flemish","native":"Nederlands"},dz:{name:"Dzongkha","native":"\u0f62\u0fab\u0f7c\u0f44\u0f0b\u0f41"},en:{name:"English","native":"English"},eo:{name:"Esperanto","native":"Esperanto"},et:{name:"Estonian","native":"eesti"},ee:{name:"Ewe","native":"E\u028begbe"},fo:{name:"Faroese","native":"f\u00f8royskt"},fj:{name:"Fijian",
"native":"vosa Vakaviti"},fi:{name:"Finnish","native":"suomi"},fr:{name:"French","native":"fran\u00e7ais"},ff:{name:"Fulah","native":"Fulfulde"},gl:{name:"Galician","native":"galego"},ka:{name:"Georgian","native":"\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8"},de:{name:"German","native":"Deutsch"},el:{name:"Greek\u00a0(modern)","native":"\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"},gn:{name:"Guaran\u00ed","native":"Ava\u00f1e'\u1ebd"},gu:{name:"Gujarati","native":"\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0"},
ht:{name:"Haitian, Haitian Creole","native":"Krey\u00f2l ayisyen"},ha:{name:"Hausa","native":"\u0647\u064e\u0648\u064f\u0633\u064e"},he:{name:"Hebrew\u00a0(modern)","native":"\u05e2\u05d1\u05e8\u05d9\u05ea"},hz:{name:"Herero","native":"Otjiherero"},hi:{name:"Hindi","native":"\u0939\u093f\u0928\u094d\u0926\u0940"},ho:{name:"Hiri Motu","native":"Hiri Motu"},hu:{name:"Hungarian","native":"magyar"},ia:{name:"Interlingua","native":"Interlingua"},id:{name:"Indonesian","native":"Bahasa Indonesia"},ie:{name:"Interlingue",
"native":"Interlingue"},ga:{name:"Irish","native":"Gaeilge"},ig:{name:"Igbo","native":"As\u1ee5s\u1ee5 Igbo"},ik:{name:"Inupiaq","native":"I\u00f1upiaq"},io:{name:"Ido","native":"Ido"},is:{name:"Icelandic","native":"\u00cdslenska"},it:{name:"Italian","native":"italiano"},iu:{name:"Inuktitut","native":"\u1403\u14c4\u1483\u144e\u1450\u1466"},ja:{name:"Japanese","native":"\u65e5\u672c\u8a9e"},jv:{name:"Javanese","native":"basa Jawa"},kl:{name:"Kalaallisut, Greenlandic","native":"kalaallisut"},kn:{name:"Kannada",
"native":"\u0c95\u0ca8\u0ccd\u0ca8\u0ca1"},kr:{name:"Kanuri","native":"Kanuri"},ks:{name:"Kashmiri","native":"\u0915\u0936\u094d\u092e\u0940\u0930\u0940"},kk:{name:"Kazakh","native":"\u049b\u0430\u0437\u0430\u049b \u0442\u0456\u043b\u0456"},km:{name:"Central Khmer","native":"\u1781\u17d2\u1798\u17c2\u179a"},ki:{name:"Kikuyu, Gikuyu","native":"G\u0129k\u0169y\u0169"},rw:{name:"Kinyarwanda","native":"Ikinyarwanda"},ky:{name:"Kirghiz, Kyrgyz","native":"\u041a\u044b\u0440\u0433\u044b\u0437\u0447\u0430"},
kv:{name:"Komi","native":"\u043a\u043e\u043c\u0438 \u043a\u044b\u0432"},kg:{name:"Kongo","native":"Kikongo"},ko:{name:"Korean","native":"\ud55c\uad6d\uc5b4"},ku:{name:"Kurdish","native":"Kurd\u00ee"},kj:{name:"Kuanyama, Kwanyama","native":"Kuanyama"},la:{name:"Latin","native":"latine"},lb:{name:"Luxembourgish, Letzeburgesch","native":"L\u00ebtzebuergesch"},lg:{name:"Ganda","native":"Luganda"},li:{name:"Limburgan, Limburger, Limburgish","native":"Limburgs"},ln:{name:"Lingala","native":"Ling\u00e1la"},
lo:{name:"Lao","native":"\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7"},lt:{name:"Lithuanian","native":"lietuvi\u0173 kalba"},lu:{name:"Luba-Katanga","native":"Tshiluba"},lv:{name:"Latvian","native":"latvie\u0161u valoda"},gv:{name:"Manx","native":"Gaelg"},mk:{name:"Macedonian","native":"\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a"},mg:{name:"Malagasy","native":"fiteny malagasy"},ms:{name:"Malay","native":"bahasa Melayu"},ml:{name:"Malayalam","native":"\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02"},
mt:{name:"Maltese","native":"Malti"},mi:{name:"Maori","native":"te reo M\u0101ori"},mr:{name:"Marathi","native":"\u092e\u0930\u093e\u0920\u0940"},mh:{name:"Marshallese","native":"Kajin M\u0327aje\u013c"},mn:{name:"Mongolian","native":"\u041c\u043e\u043d\u0433\u043e\u043b \u0445\u044d\u043b"},na:{name:"Nauru","native":"Ekakair\u0169 Naoero"},nv:{name:"Navajo, Navaho","native":"Din\u00e9 bizaad"},nd:{name:"North Ndebele","native":"isi Ndebele"},ne:{name:"Nepali","native":"\u0928\u0947\u092a\u093e\u0932\u0940"},
ng:{name:"Ndonga","native":"Owambo"},nb:{name:"Norwegian Bokm\u00e5l","native":"Norsk bokm\u00e5l"},nn:{name:"Norwegian Nynorsk","native":"Norsk nynorsk"},no:{name:"Norwegian","native":"Norsk"},ii:{name:"Sichuan Yi, Nuosu","native":"\ua188\ua320\ua4bf Nuosuhxop"},nr:{name:"South Ndebele","native":"isi Ndebele"},oc:{name:"Occitan","native":"occitan"},oj:{name:"Ojibwa","native":"\u140a\u14c2\u1511\u14c8\u142f\u14a7\u140e\u14d0"},cu:{name:"Church\u00a0Slavic, Church\u00a0Slavonic,\u00a0Old\u00a0Church\u00a0Slavonic, Old\u00a0Slavonic,\u00a0Old\u00a0Bulgarian",
"native":"\u0469\u0437\u044b\u043a\u044a \u0441\u043b\u043e\u0432\u0463\u043d\u044c\u0441\u043a\u044a"},om:{name:"Oromo","native":"Afaan Oromoo"},or:{name:"Oriya","native":"\u0b13\u0b21\u0b3c\u0b3f\u0b06"},os:{name:"Ossetian, Ossetic","native":"\u0438\u0440\u043e\u043d \u00e6\u0432\u0437\u0430\u0433"},pa:{name:"Panjabi, Punjabi","native":"\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40"},pi:{name:"Pali","native":"\u092a\u093e\u0934\u093f"},fa:{name:"Persian","native":"\u0641\u0627\u0631\u0633\u06cc"},pl:{name:"Polish",
"native":"j\u0119zyk polski"},ps:{name:"Pashto, Pushto","native":"\u067e\u069a\u062a\u0648"},pt:{name:"Portuguese","native":"portugu\u00eas"},qu:{name:"Quechua","native":"Runa Simi"},rm:{name:"Romansh","native":"rumantsch grischun"},rn:{name:"Rundi","native":"Ikirundi"},ro:{name:"Romanian, Moldavian, Moldovan","native":"limba rom\u00e2n\u0103"},ru:{name:"Russian","native":"\u0420\u0443\u0441\u0441\u043a\u0438\u0439"},sa:{name:"Sanskrit","native":"\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d"},
sc:{name:"Sardinian","native":"sardu"},sd:{name:"Sindhi","native":"\u0938\u093f\u0928\u094d\u0927\u0940"},se:{name:"Northern Sami","native":"Davvis\u00e1megiella"},sm:{name:"Samoan","native":"gagana fa'a Samoa"},sg:{name:"Sango","native":"y\u00e2ng\u00e2 t\u00ee s\u00e4ng\u00f6"},sr:{name:"Serbian","native":"\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a"},gd:{name:"Gaelic, Scottish Gaelic","native":"G\u00e0idhlig"},sn:{name:"Shona","native":"chiShona"},si:{name:"Sinhala, Sinhalese",
"native":"\u0dc3\u0dd2\u0d82\u0dc4\u0dbd"},sk:{name:"Slovak","native":"sloven\u010dina"},sl:{name:"Slovenian","native":"sloven\u0161\u010dina"},so:{name:"Somali","native":"Soomaaliga"},st:{name:"Southern Sotho","native":"Sesotho"},es:{name:"Spanish, Castilian","native":"espa\u00f1ol"},su:{name:"Sundanese","native":"Basa Sunda"},sw:{name:"Swahili","native":"Kiswahili"},ss:{name:"Swati","native":"SiSwati"},sv:{name:"Swedish","native":"svenska"},ta:{name:"Tamil","native":"\u0ba4\u0bae\u0bbf\u0bb4\u0bcd"},
te:{name:"Telugu","native":"\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41"},tg:{name:"Tajik","native":"\u0442\u043e\u04b7\u0438\u043a\u04e3"},th:{name:"Thai","native":"\u0e44\u0e17\u0e22"},ti:{name:"Tigrinya","native":"\u1275\u130d\u122d\u129b"},bo:{name:"Tibetan","native":"\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42"},tk:{name:"Turkmen","native":"T\u00fcrkmen"},tl:{name:"Tagalog","native":"Wikang Tagalog"},tn:{name:"Tswana","native":"Setswana"},to:{name:"Tonga\u00a0(Tonga Islands)","native":"faka Tonga"},
tr:{name:"Turkish","native":"T\u00fcrk\u00e7e"},ts:{name:"Tsonga","native":"Xitsonga"},tt:{name:"Tatar","native":"\u0442\u0430\u0442\u0430\u0440 \u0442\u0435\u043b\u0435"},tw:{name:"Twi","native":"Twi"},ty:{name:"Tahitian","native":"Reo Tahiti"},ug:{name:"Uighur, Uyghur","native":"\u0626\u06c7\u064a\u063a\u06c7\u0631\u0686\u06d5"},uk:{name:"Ukrainian","native":"\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430 \u043c\u043e\u0432\u0430"},ur:{name:"Urdu","native":"\u0627\u0631\u062f\u0648"},
uz:{name:"Uzbek","native":"O\u02bbzbek"},ve:{name:"Venda","native":"Tshiven\u1e13a"},vi:{name:"Vietnamese","native":"Ti\u1ebfng Vi\u1ec7t"},vo:{name:"Volap\u00fck","native":"Volap\u00fck"},wa:{name:"Walloon","native":"walon"},cy:{name:"Welsh","native":"Cymraeg"},wo:{name:"Wolof","native":"Wollof"},fy:{name:"Western Frisian","native":"Frysk"},xh:{name:"Xhosa","native":"isiXhosa"},yi:{name:"Yiddish","native":"\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9"},yo:{name:"Yoruba","native":"Yor\u00f9b\u00e1"},za:{name:"Zhuang, Chuang",
"native":"Sa\u026f cue\u014b\u0185"},zu:{name:"Zulu","native":"isiZulu"}},f=function(a){a=e[a];return null==a?"":a.native},n=function(a){return e[a]},q=function(a,f){if(null==a)return null;a=a[f];return null==a?null:a.message},p=function(k,f){"zh"==k&&(k="zh_CN");var e=a[k];if(null!=e)return f(e);var u=k.split("-")[0];e=a[u];if(null!=e)return f(e);e=chrome.extension.getURL("_locales/"+k+"/messages.json");Utils.UrlGet(e,null,function(e,p){if(e&&null!=p)return a[k]=p,a[u]=p,f(p);e=chrome.extension.getURL("_locales/"+
u+"/messages.json");Utils.UrlGet(e,null,function(e,p){return e&&null!=p?(a[k]=p,a[u]=p,f(p)):f(null)})})};return{constructor:Langs$,GetNativeName:function(){return f.apply(this,arguments)},GetLanguage:function(){return n.apply(this,arguments)},GetLocale:function(){return p.apply(this,arguments)},GetLocaleMessage:function(){return q.apply(this,arguments)}}}();var Langs=new Langs$;String.isNullOrEmpty||(String.isNullOrEmpty=function(a){return null==a||""==a});String.prototype.in=String.prototype.in||function(){return 0<=arguments.indexOf(this)};Date.prototype.isValid=Date.prototype.isValid||function(){return!isNaN(this.getTime())};Array.prototype.last=Array.prototype.last||function(){return 0<this.length?this[this.length-1]:null};Array.prototype.first=Array.prototype.first||function(){return 0<this.length?this[0]:null};
$.extend($.expr[":"],{"node-names":function(a,e,f){return 0<=f[3].toLowerCase().split(",").indexOf(a.nodeName.toLowerCase())},startsWith:function(a,e,f){a=(a.innerText||"").trim().replace(/[\s]/g," ");return null!=a&&""!=a&&a.startsWith(f[3])},prefixes:function(a,e,f){a=(a.innerText||"").trim().replace(/[\s]/g," ");if(""!=a){prefixes=f[3]||"";f=[];if(prefixes.startsWith("'"))for(e=/'([^']*)'/g;match=e.exec(prefixes);)f.push(match[1]);else f.push(prefixes);e=0;for(var n=f.length;e<n;e++)if(a.startsWith(f[e]))return!0}return!1},
"has-text":function(a,e,f){if(0<=f[3].toLowerCase().split(",").indexOf(a.nodeName.toLowerCase()))for(e=0,f=a.childNodes.length;e<f;++e){var n=a.childNodes[e];if(3==n.nodeType&&/\S/.test(n.nodeValue))return!0}return!1}});function Utils$(){}
Utils$.prototype=function(){var a=function(c){console.log.apply(this,arguments)},e=function(c){console.warn.apply(this,arguments)},f=function(c){console.error.apply(this,arguments)},n=function(){return window.navigator.userLanguage||window.navigator.language},q=function(c,g,b){null!=c&&0!=c&&clearTimeout(c);return setTimeout(b,g)},p=function(c){clearTimeout(c);return null},k=function(c){var g=1<arguments.length?Array.prototype.slice.call(arguments,1):[];return chrome.i18n.getMessage.apply(this,[c,
g])},z=function(c,g){"string"==typeof c&&(null==g&&(g=c),c=$(c));null==g&&(g=c.prop("id"));if(!String.isNullOrEmpty(g)){g.startsWith("#")&&(g=g.substring(1,g.legnth));var b=Array.prototype.slice.call(arguments,1);b[0]=g;b=chrome.i18n.getMessage.apply(this,b);c.text(b)}},w=function(c){var g=null;c=c.match(/.+?:\/\/(.+?)\//);null!=c&&1<c.length&&(g=c[1].toLowerCase(),c=g.substring(0,4),"www."==c||"ww2."==c)&&(g=g.substring(4,g.length));return g},u=function(){return chrome.extension.getBackgroundPage().Background},
B=function(c){null==c&&(c=0);return parseInt(Date.now()/1E3)+c},r=function(c){return null==c?"":(new Date(c)).toJSON().split("T")[0]},A=function(c){if(null==c||null!=c.isValiad&&!c.isValid())return"";c=(new Date(c)).toJSON();c=c.split(".")[0];return c.split("T").join(" ")},x=function(c){return null==c?null:JSON.stringify(c,null,2)},v=function(c,g){if(String.isNullOrEmpty(c))return null;try{return JSON.parse(c)}catch(R){if(g)return null;throw R;}},E=function(c,g,b,d,a){a=a||function(){};return $.ajax(g,
{timeout:12E4,type:c,headers:b,data:d,success:function(c,g,b){a(!0,c,b)},error:function(c,b,d){String.isNullOrEmpty(d)&&(d=b);0==c.status&&null!=d&&"error"==d.toLowerCase()&&(d=k("error_connection_refused",w(g)));a(!1,d,c)}})},C=function(c,g,b,d,a){a=a||function(){};return $.ajax(g,{timeout:12E4,type:c,dataType:"json",headers:b,data:x(d),success:function(c,g,b){a(!0,c,b)},error:function(c,b,d){String.isNullOrEmpty(d)&&(d=b);0==c.status&&null!=d&&"error"==d.toLowerCase()&&(d=k("error_connection_refused",
w(g)));a(!1,d,c)}})},F=function(c,g,b){return E("GET",c,g,null,b)},D=function(c,g,b){return C("GET",c,g,null,b)},h=function(c,g,b,d){return C("POST",c,g,b,d)},t=function(c,g,b,d){return C("PUT",c,g,b,d)},b=function(c,g){"string"==typeof c&&(c=$(c));c.toggle(g)},d=function(c,g){"string"==typeof c&&(c=$(c));c.toggleClass("ui-state-disabled",!g)},l=function(c){"string"==typeof c&&(c=$(c));return c.is(":checked")},y=function(c,g){"string"==typeof c&&(c=$(c));c.prop("checked",g)},S=function(c,g){"string"==
typeof c&&(c=$(c));c.toggleClass("ui-state-disabled",g)},T=function(c,g,b){c=c.replace(/\n/g,"<br/>");c=String.isNullOrEmpty(b)?"<p>"+c+"</p>":"<table cellpadding='4'><tr><td valign='top'><span class='ui-icon "+b+"'/></td><td>"+c+"</td></tr></table>";g=$.extend({modal:!0,title:k("extName"),maxHeight:525,maxWidth:500,width:450,buttons:{Ok:function(){$(this).dialog("close")}}},g);$(c).dialog(g)},U=function(c,g,b){c="<p>"+c+"</p>";var d={};d[k("label_confirm")]=function(){$(this).dialog("close");b(!0)};
d[k("label_cancel")]=function(){$(this).dialog("close");b(!1)};g=$.extend({modal:!0,title:k("extName"),maxHeight:525,maxWidth:500,width:450,buttons:d},g);$(c).dialog(g)},V=function(c,g,b){c="<div><p>"+c+'</p><input type="text" class="ui-width-100" value="'+g+'"/></div>';g={};g[k("label_ok")]=function(){$(this).dialog("close");b(!0,$(this).find("input").val())};g[k("label_cancel")]=function(){$(this).dialog("close");b(!1,"")};var d=$.extend({modal:!0,title:k("extName"),maxHeight:525,maxWidth:500,width:450,
buttons:g,open:function(){$(this).find("input").select()}},d);$(c).dialog(d)},M=function(c,g,b){b=b||document;b=b.createElement(c);if(null!=g)for(c in g)b[c]=g[c];return b},I=function(c,g,b,d){g=M(g,b,d);c.appendChild(g);return g},N=function(c,g,b){g=g||document;var d=g.getElementsByTagName("head")[0];I(d,"link",{type:"text/css",rel:"stylesheet",href:c,onload:b},g)},W=function(c,g,b){g=g||document;var d=g.getElementsByTagName("head")[0];I(d,"script",{type:"text/javascript",onload:b,src:c},g)},X=function(c,
g,b){N("../lib/jquery-ui/themes/"+c+"/jquery-ui.css",g,b)},Y=function(c,g,b,d){c.append($("<option>",{value:g,text:b,title:d||b}))},Z=function(c,b){b=$("<textarea>").text(b).appendTo(c.parent()).focus().select();document.execCommand("copy");b.remove();c.focus()},aa=function(c){chrome.tabs.create({url:c},function(c){})},ba=function(c,b){var g=function(c){var g=c.id;0>g&&(g=0);b(c,g,w(c.url),c.url)};if(null!=c)return g(c);chrome.tabs.getSelected(g)},J=function(c){0<c.length&&c[0].scrollIntoViewIfNeeded()},
ca=function(c,b){var g=[];if(null!=c){c=c.split(b);for(var d=0,a=c.length;d<a;d++){var l=c[d];d<a-1&&(l+=b);g.push(l)}}return g},da=function(c,b){var g=[];$.each(c.split("\n"),function(c,d){g.push(O(d,b))});return g},P=function(c,b){for(var g=0,d=0,a=b.length;0<=(d=c.indexOf(b,d));)g++,d+=a;return g},G=function(c,b,d){d=d||-1;$.each(b,function(b,g){b=c.lastIndexOf(g);0<=b&&(b+=g.length,b>d&&(d=b))});return d},Q=function(c,b,d){d=d||-1;$.each(b,function(b,g){b=c.lastIndexOf(g);0<b&&b>d&&(d=b)});return d},
ea=function(c,b,d,a){var g=c.length;if(0>b||b>=g)return"";for(var l=b;0<=l&&l<g&&a(c[l]);)l+=d?-1:1;return 0>l?d?c.substring(0,b+1):c.substring(b):d?c.substring(l+1,b+1):c.substring(b,l)},fa=function(c,b){b=b||-1;for(var d=c.lastIndexOf(". ");d>b;){var g=ea(c,d,!0,function(c){return"."==c||"a"<=c&&"z">=c||"A"<=c&&"Z">=c});g=g.toLowerCase().trim();if("."==g||!Consts.AbbrWords[g])return d+1;d=c.lastIndexOf(". ",d-1)}return b},O=function(c,b){c=c.replace(/\n/g," ").replace(/\r/g," ");for(var d=[],g=
new RegExp("^.{1,"+b+"}\\b"),a=function(){var d=c.match(g);d=null==d||0==d.length?c.substring(0,b):d[0].trimEnd();var a=G(d,['."',"\u3002\u201d","\u3002","\uff1f"],-1);a=G(d,['."','".',"? "],a);a=fa(d,a);if(0<a||0<(a=G(d,["; "]))||0<(a=G(d,[", ","\uff0c"])))return a;a=G(d,"\u201d\uff09\uff3d\uff5d\u3001\uff1a".split(""),a);a=G(d,'.";" ;) ;] ;} ;: '.split(";"),a);a=Q(d,["\u201c","\uff08","\uff3b","\uff5b "],a);a=Q(d,[" ("," ["," {"],a);if(0<a)return a;var l=d.length;for(a=d.lastIndexOf(" ",l-1);0<
a;){l=d.substring(a+1,l).trim();if(""!=l&&Consts.StopWords[l])return a+1;l=a;a=d.lastIndexOf(" ",l-1)}return d.length};c.length>b;){var l=a();0>=l&&(l=b);d.push(c.substring(0,l));c=c.substring(l)}""!=c&&d.push(c);return d},H=function(c,b){for(var d=c.length;0<d;){var g=c.lastIndexOf('"',d);d=c.lastIndexOf(b,d);if(d>g)return d;d=c.lastIndexOf('"',g-1)-1}return-1},ha=function(c){var b,d=c.length;if(0<(b=H(c,"\u201c")))return c.substring(0,b);if(0<(b=H(c,"\u201d")))return c.substring(0,b+1);if(0<(b=
H(c,"; "))||0<(b=H(c,", "))||0<(b=H(c,": ")))return c.substring(0,b+2);b=c.lastIndexOf('"');if(0<b)return 0==P(c,'"')%2&&(b+=1),b<d&&"."==c[b]&&(b+=1),c.substring(0,b);if(0<(b=H(c,Consts.TtsIdPrefix)))return b=c.indexOf(Consts.TtsIdSurfix,b),c.substring(0,b+1);for(;0<d;){start=c.lastIndexOf(" ",d-1);0>start&&(start=0);b=c.substring(start+1,d);if(""!=b&&Consts.StopWords[b])return c.substring(0,start+1);d=start}return c},K=function(c,b){var d=function(c){b({selection:Langs.GetLocaleMessage(c,"text_voice_template_selection"),
paragraph:Langs.GetLocaleMessage(c,"text_voice_template_paragraph"),article:Langs.GetLocaleMessage(c,"text_voice_template_article")})};Langs.GetLocale(c,function(c){return null!=c?d(c):Langs.GetLocale("en",d)})},ia=function(c,b){var d=function(c){b({title:Langs.GetLocaleMessage(c,"text_voice_exmaple_title"),author:Langs.GetLocaleMessage(c,"text_voice_exmaple_author"),time:Langs.GetLocaleMessage(c,"text_voice_exmaple_time"),body:Langs.GetLocaleMessage(c,"text_voice_exmaple_body")})};Langs.GetLocale(c,
function(c){return null!=c?d(c):Langs.GetLocale("en",d)})},ja=function(c,b){var d="";String.isNullOrEmpty(c)||(d=c.split("-")[0]);String.isNullOrEmpty(d)&&(d="en");c=Settings.Data.VoiceTemplates[d];if(null!=c&&null!=c.templates)return b(c.templates);K(d,function(c){if(null!=c)return b(c);c=Settings.Data.VoiceTemplates[d];return null!=c&&null!=c.templates?b(c.templates):K("en",b)})},ka=function(c,b){c=c||{};return null==b?c.body:b.replace(/\{title\}/,c.title||"").replace(/\{author\}/,c.author||"").replace(/\{time\}/,
c.time||"").replace(/\{language\}/,Langs.GetNativeName(c.language||"")).replace(/\{body\}/,c.body||"")},la=function(c,b,d){L(c,MessageCommand.GetLanguage,null,null,function(a){a=String.isNullOrEmpty(a)?null:a.split("-")[0];if(""!=Langs.GetNativeName(a))return d(a);if(!b)return d(null);L(c,MessageCommand.GetTitle,null,null,function(c){c=(c||"").trim();if(String.isNullOrEmpty(c))return d(null);chrome.i18n.detectLanguage(c,function(c){return null!=c&&c.isReliable&&null!=c.languages&&0<c.languages.length&&
(c=c.languages[0],null!=c)?d(c.language.split("-")[0]):d(null)})})})},ma=function(c,b){chrome.identity.removeCachedAuthToken({token:c},function(){D(Config.RevokeUrl+c,null,function(c,d){return c?b(!0,"Token is revoked"):b(!1,"Failed to revoke token")})})},na=function(c,b){chrome.identity.getAuthToken({interactive:!0},function(d){if(chrome.runtime.lastError)return b(!1,chrome.runtime.lastError);D(c,{Authorization:"Bearer "+d},function(c,d,a){if(!c)return b(!1,d);if(null==d)return b(!1,"failed to get license server");
if(d.result&&"FULL"==d.accessLevel)b(!0,"FULL");else return d.result&&"FREE_TRIAL"==d.accessLevel?(Date.now()-parseInt(d.createdTime,10))/1E3/60/60/24<=Config.TrialDays?b(!0,"FREE_TRIAL"):b(!1,"Free trial ended already"):b(!1,"Please subscribe first")})})},L=function(c,b,d,a,l){chrome.tabs.sendMessage(c,{event:b,data:d},l)},oa=function(c){return Consts.TtsIdBuilder.replace("{0}",c)},pa=function(c){var b=[];c=c.replace(new RegExp(Consts.TtsIdRemover,"ig"),function(c,d,a,g){0>b.indexOf(d)&&b.push(d);
return""});return{text:c,ttsIds:b}},qa=function(c,b){if(null==c||""==c)return b;Array.isArray(c)?c.push(b):c=[c,b];return c},ra=function(c,b){null!=c&&""!=c&&(c=1==b?c.replace(/\s*\n+\s*/g,"\n").replace(/[ ]+/g," "):c.replace(/\s+/g," "),c=c.trim());return c},sa=function(c,b){String.isNullOrEmpty(c)||("string"==typeof b&&(b=[b]),$.each(b,function(b,d){d=d.toLowerCase();b=c.substring(0,Math.min(d.length+1,c.length)).toLowerCase();if(b==d+" "||b==d+":")c=c.substring(d.length+1,c.length)}));return c},
ta=function(c,b){b=b?new RegExp("^"+b+"+|"+b+"+$","g"):/^\s+|\s+$/g;return c.trim().replace(b,"").trim()},ua=function(c,b){b=b?new RegExp(b+"+$"):/\s+$/;return c.trim().replace(b,"").trim()},va=function(c,b){b=b?new RegExp("^"+b+"+"):/^\s+/;return c.trim().replace(b,"").trim()},wa=function(c){null!=c&&""!=c&&(c=c.toLowerCase().replace(/([^a-z])([a-z])(?=[a-z]{1})|^([a-z])/g,function(c,b,d,a){return"undefined"===typeof b?a.toUpperCase():b+d.toUpperCase()}));return c},xa=function(c,b){var d=new JSEncrypt;
d.setPublicKey(c);return d.encrypt(b)},ya=function(c,b,d){if(String.isNullOrEmpty(c))return"";for(var a=end="",l=-1,g=-1,h=0,y=b.length;h<y&&!(a=b[h],l=c.indexOf(a),0<=l);h++);if(""==a||0>l)return"";h=0;for(y=d.length;h<y&&!(end=d[h],g=c.lastIndexOf(end),0<=g);h++);return""==end||0>g?"":c.substring(l,g+end.length)},za=function(c,b,d){for(var a=0,l=b.length;a<l;a++){var g=c.indexOf(b[a],d);if(0<=g)return g}return-1},Aa=function(b,d,a,l){query=encodeURIComponent(b);D("https://www.google.com/async/dictw?async=term:"+
query+",corpus:"+a,null,function(b,c){var d={},a=null,g=null;b&&c&&2<=c.length&&(a=c[1])&&2<=a.length&&(g=a[1])&&(b=!1,g=g.replace(/src="/g,'_src="').replace(/srcset="/g,'_srcset="'),$(g).find(".lr_dct_ent>.vmod>.vmod").each(function(b,c){b=$(c);c=b.find("i:first").text();var a=d[c];null==a&&(d[c]=a=[]);b.find(">ol>li:lt(2)").each(function(b,c){b=$(c).find("div[data-dobid='dfn']>span:first").text();""!=b&&a.push(b)})}));var h="",y;for(y in d)b=d[y],h+="<div>"+y+"</div><ol>",$.each(b,function(){h+=
"<li>"+this+"</li>"}),h+="</ol></div>";l(""!=h,h)})},Ba=function(b,d,a,l){b=encodeURIComponent(b);D("https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl="+a+"&dt=bd&q="+b,null,function(b,c){var d=$("<div>");b&&c&&2<=c.length&&$.each(c[1],function(b,c){b=$("<div>").text(c[0]);var a=$("<ol>");c=$("<li>").text(c[1].join(", "));a.append(c).appendTo(b);d.append(b)});l(0<d.find("div").length,d.html())})},Ca=function(b,d,a,l){b=encodeURIComponent(b);D("https://"+a+".wikipedia.org/w/api.php?action=query&prop=extracts&titles="+
b+"&exintro=&exsentences=2&explaintext=&redirects=&formatversion=2&format=json",null,function(b,c){if(b&&c&&c.query&&c.query.pages&&(b=c.query.pages[0])&&!b.missing&&!b.invalid){var d=(b.extract||"").trim();if(""!=d)return l(!0,b.extract)}l(!1,d)})},Da=function(b,d,a,l){var c=[],g="";$.each(b.split("\n"),function(b,d){d=encodeURIComponent(d);6144<g.length+d.length?(c.push(g),g=d):(""!=g&&(g+=encodeURIComponent("\n")),g+=d)});""!=g&&c.push(g);b="";var h=function(d){if(d>=c.length)return l(!0,b);D("https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl="+
a+"&dt=t&q="+c[d],null,function(c,a){c&&0<a.length&&$.each(a[0],function(c,d){b+=d[0]});h(d+1)})};h(0)},Ea=function(b,d,a){var c=function(l){if(l>=b.length)return a(!0);d(l,b[l],function(b){if(b)return a(!1);c(l+1)})};c(0)},Fa=function(){return chrome.runtime.getManifest()},Ga=function(b,d){b=b||"";1024<b.length&&(b=b.substring(0,1024));chrome.i18n.detectLanguage(b,function(b){if(null!=b&&null!=b.languages&&0<b.languages.length){var c=b.languages[0];if(b.isReliable||85<=c.percentage)return d(c.language.split("-")[0])}return d(null)})},
Ha=function(b){return chrome.extension.getURL(b)},Ia=function(b,d){if(null==b||""==b)return"";b=b.match(d);return null!=b&&1<b.length?b[1]:""};return{LogInfo:function(){return a.apply(this,arguments)},LogWarn:function(){return e.apply(this,arguments)},LogError:function(){return f.apply(this,arguments)},GetUserLanguage:function(){return n.apply(this,arguments)},SetTimeout:function(){return q.apply(this,arguments)},ClearTimeout:function(){return p.apply(this,arguments)},GetMessage:function(){return k.apply(this,
arguments)},SetLocaleText:function(){return z.apply(this,arguments)},GetUrlHost:function(){return w.apply(this,arguments)},Background:function(){return u.apply(this,arguments)},NowInSeconds:function(){return B.apply(this,arguments)},GetDate:function(){return r.apply(this,arguments)},GetDateTime:function(){return A.apply(this,arguments)},ToJsonString:function(){return x.apply(this,arguments)},UrlRequest:function(){return C.apply(this,arguments)},UrlGetRaw:function(){return F.apply(this,arguments)},
UrlGet:function(){return D.apply(this,arguments)},UrlPost:function(){return h.apply(this,arguments)},UrlPut:function(){return t.apply(this,arguments)},ShowElement:function(){return b.apply(this,arguments)},EnableElement:function(){return d.apply(this,arguments)},IsChecked:function(){return l.apply(this,arguments)},CheckButton:function(){return y.apply(this,arguments)},DisableBox:function(){return S.apply(this,arguments)},MessageBox:function(){return T.apply(this,arguments)},Confirm:function(){return U.apply(this,
arguments)},Prompt:function(){return V.apply(this,arguments)},CreateElement:function(){return M.apply(this,arguments)},AppendChild:function(){return I.apply(this,arguments)},AppendStyleUrl:function(){return N.apply(this,arguments)},AppendScriptUrl:function(){return W.apply(this,arguments)},ApplyTheme:function(){return X.apply(this,arguments)},AppendSelectOption:function(){return Y.apply(this,arguments)},CopyToClipboard:function(){return Z.apply(this,arguments)},OpenNewTab:function(){return aa.apply(this,
arguments)},GetTabInfo:function(){return ba.apply(this,arguments)},ScrollIntoView:function(){return J.apply(this,arguments)},BreakTextToBlocks:function(){return da.apply(this,arguments)},GetSubStrCount:function(){return P.apply(this,arguments)},BreakLineToBlocks:function(){return O.apply(this,arguments)},BreakTextByQuoatAndWord:function(){return ha.apply(this,arguments)},GetVoiceTemplateFromLocale:function(){return K.apply(this,arguments)},GetArticleExampleFromLocale:function(){return ia.apply(this,
arguments)},GetVoiceTemplateByLanguage:function(){return ja.apply(this,arguments)},GetArticleTextByTemplate:function(){return ka.apply(this,arguments)},GetTabLanguage:function(){return la.apply(this,arguments)},RevokeToken:function(){return ma.apply(this,arguments)},CheckLicense:function(){return na.apply(this,arguments)},SendMessage:function(){return L.apply(this,arguments)},BuildTtsId:function(){return oa.apply(this,arguments)},AddToArray:function(){return qa.apply(this,arguments)},ReduceWhitespaces:function(){return ra.apply(this,
arguments)},RemovePrefix:function(){return sa.apply(this,arguments)},Trim:function(){return ta.apply(this,arguments)},TrimLeft:function(){return va.apply(this,arguments)},TrimRight:function(){return ua.apply(this,arguments)},ToUpperCaseFirstLetters:function(){return wa.apply(this,arguments)},RsaEncryption:function(){return xa.apply(this,arguments)},ParseJson:function(){return v.apply(this,arguments)},SubstrByTags:function(){return ya.apply(this,arguments)},IndexOfAny:function(){return za.apply(this,
arguments)},Translate:function(){return Da.apply(this,arguments)},GetManifest:function(){return Fa.apply(this,arguments)},SplitTextToItems:function(){return ca.apply(this,arguments)},DetectLanguage:function(){return Ga.apply(this,arguments)},RemoveTtsIds:function(){return pa.apply(this,arguments)},GetWiki:function(){return Ca.apply(this,arguments)},GetDict:function(){return Ba.apply(this,arguments)},GetDefine:function(){return Aa.apply(this,arguments)},EachAsync:function(){return Ea.apply(this,arguments)},
ExtGetUrl:function(){return Ha.apply(this,arguments)},GetFirstMatch:function(){return Ia.apply(this,arguments)},constructor:Utils$}}();var Utils=new Utils$;function Db$(){}
Db$.prototype=function(){var a=function(a,k){var f="site:"+a.toLowerCase();chrome.storage.local.get(f,function(a){try{var e=a[f];if(null!=e&&""!=e)return k(JSON.parse(e))}catch(v){Utils.LogError("Failed to parse json: "+v)}return k(null)})},e=function(a,k,f){a="site:"+a.toLowerCase();var e={};e[a]=JSON.stringify(k);chrome.storage.local.set(e,f)},f=function(a,k){a="site:"+a.toLowerCase();chrome.storage.local.remove(a,k)},n=function(a){chrome.storage.local.get(null,function(k){var f=[];$.each(Object.keys(k),
function(a,e){if(e.startsWith("book:"))try{f.push(JSON.parse(k[e]))}catch(v){}});a(f)})},q=function(a,k){var f="book:"+a.toLowerCase();chrome.storage.local.get(f,function(a){try{var e=JSON.parse(a[f]);return k(e)}catch(v){}return k(null)})},p=function(a,k,f){a="book:"+a.toLowerCase();var e={};e[a]=JSON.stringify(k);chrome.storage.local.set(e,f)},k=function(a,k){a="book:"+a.toLowerCase();chrome.storage.local.remove(a,k)},z=function(a){chrome.storage.local.get("settings:",function(k){a(k["settings:"])})},
w=function(a,k){var f={};f["settings:"]=a;chrome.storage.local.set(f,k)};return{constructor:Db$,GetSite:function(){return a.apply(this,arguments)},SaveSite:function(){return e.apply(this,arguments)},RemoveSite:function(){return f.apply(this,arguments)},GetBooks:function(){return n.apply(this,arguments)},GetBook:function(){return q.apply(this,arguments)},SaveBook:function(){return p.apply(this,arguments)},RemoveBook:function(){return k.apply(this,arguments)},GetSettings:function(){return z.apply(this,
arguments)},SaveSettings:function(){return w.apply(this,arguments)}}}();var Db=new Db$;function Repo$(){}
Repo$.prototype=function(){var a=function(a,f,e){Db.GetSite(a,function(k){if(null!=k){var n=Utils.NowInSeconds()-k.cachedTime;if(0<=n&&n<=Consts.SiteExpireInSeconds)return e(ErrorCode.None,k)}if(f)return e(ErrorCode.None,null);n=null==k?null:k.lastModified;if(null!=k&&0<k.id&&0==k.official)return Service.GetSiteById(k.id,n,function(f,n,x){p(f,a,k,n,x,e)});Service.GetPrimarySite(a,n,function(f,n,x){p(f,a,k,n,x,e)})})},e=function(a,f){null==a.createdTime&&(a.cachedTime=a.createdTime=Utils.NowInSeconds());
a.updatedTime=Utils.NowInSeconds();Db.SaveSite(a.host,a,f)},f=function(a,f){Db.RemoveSite(a,f)},n=function(a){Db.GetSettings(a)},q=function(a,f){null!=a&&Db.SaveSettings(a,f)},p=function(a,f,p,n,q,r){if(a!=ErrorCode.None)return r(a,n);switch(q.status){case 200:a=n.template;if(String.isNullOrEmpty(a))return r(ErrorCode.None,null);try{n.template=JSON.parse(a)}catch(A){return Utils.LogError("Invalid site template, Host:'${site.host}', Id:'${site.id}', temmplate:'${site.template}'"),r(ErrorCode.None,
null)}n.lastModified=parseInt(q.getResponseHeader("Last-Modified"));n.cachedTime=Utils.NowInSeconds();n.verified=!0;n.published=!0;n.visible=null!=p?p.visible:!1;e(n);return r(ErrorCode.None,n);case 304:return p.cachedTime=Utils.NowInSeconds(),e(p),r(ErrorCode.None,p);case 404:return null!=p?(p.cachedTime=Utils.NowInSeconds(),e(p),r(ErrorCode.None,p)):r(ErrorCode.NoTemplate,Utils.GetMessage("error_article_no_template",f));default:return r(ErrorCode.SystemError,n)}};return{GetSite:function(){return a.apply(this,
arguments)},SaveSite:function(){return e.apply(this,arguments)},RemoveSite:function(){return f.apply(this,arguments)},GetSettings:function(){return n.apply(this,arguments)},SaveSettings:function(){return q.apply(this,arguments)},constructor:Repo$}}();var Repo=new Repo$;function Extractor$(){}
Extractor$.prototype=function(){var a=function(b,d,a){Utils.GetTabInfo(b,function(b,l,h,f){z(l,d,function(b){Utils.DetectLanguage(b,function(d){u(l,h,!0,function(l,f){if(l!=ErrorCode.None)return a(l,f);l={body:b,language:w(d,f),host:h};return a(ErrorCode.None,l)})})})})},e=function(b,d){Utils.GetTabInfo(b,function(b,a,h,f){Utils.SendMessage(a,MessageCommand.GetParagraph,null,null,function(b){var l=x(b);Utils.DetectLanguage(l,function(b){u(a,h,!0,function(a,f){if(a!=ErrorCode.None)return d(a,f);a=
{body:l,language:w(b,f),host:h};return d(ErrorCode.None,a)})})})})},f=function(b,d,a,h){Utils.GetTabInfo(b,function(b,l,f,e){Repo.GetSiteByHost(f,d,function(d,l){return d!=ErrorCode.None?h(d,l):q(b,l,a,h)})})},n=function(b,d,a){chrome.webNavigation.getAllFrames({tabId:b},function(b){var l=0;$.each(b,function(b,a){if(b==d)return l=a.frameId,!1});a(l)})},q=function(b,d,a,h){if("string"==typeof b)return t(b,d,h);Utils.GetTabInfo(b,function(b,l,f,e){B(l,d,function(b,d,e){if(b!=ErrorCode.None)return h(b,
d);if(null==d)return h(ErrorCode.None,d);var y=("string"==typeof d.article?d.article:d.article.select)||"";y.endsWith(":first")||(y+=":first");n(l,0,function(b){b=0;Utils.SendMessage(l,MessageCommand.GetDocument,{select:y,needTag:a},b,function(a){a=(a||"").trim();if(String.isNullOrEmpty(a))return h(ErrorCode.NoDocument,Utils.GetMessage("error_document_no_text"));try{var l=p(a),y=k(a),t=v(l,y,f,d);if(null==t)return h(ErrorCode.None,null);t.host=f;t.pageIdx=e;t.frameId=b;if("object"==typeof d.language&&
(0==d.language.auto||"false"==d.language.auto))return t.language=d.language.default,h(ErrorCode.None,t);Utils.DetectLanguage(t.body,function(b){t.language=w(b,d);h(ErrorCode.None,t)})}catch(J){return h(ErrorCode.ParseArticleError,Utils.GetMessage("error_parse_article",J.message))}})})})})},p=function(b){b=b.replace(/src=/gi,"_src=").replace(/srcset=/gi,"_srcset=").replace(/<html>/i,"<doc>").replace(/<html /i,"<doc ").replace(/<\/html>/i,"</doc>");b=$(b);b.find("style,iframe").remove();return b},k=
function(b){b=Utils.SubstrByTags(b,["<body>","<body ","<BODY>","<BODY "],["</body>","</BODY>"]);b=b.replace(/src=/gi,"_src=").replace(/srcset=/gi,"_srcset=").replace(/<body>/i,"<div>").replace(/<body /i,"<div ").replace(/<\/body>/i,"</div>");b=$(b);b.find("style,iframe").remove();return b},z=function(b,d,a){if(!String.isNullOrEmpty(d))return a(d);Utils.SendMessage(b,MessageCommand.GetSelection,null,null,a)},w=function(b,d){String.isNullOrEmpty(b)&&null!=d&&(b=d.language);return String.isNullOrEmpty(b)?
"en":b.split("-")[0]},u=function(b,d,a,h){Repo.GetSiteByHost(d,a,function(d,a){return d!=ErrorCode.None?h(d,a):B(b,a,h)})},B=function(b,d,a){if(null==d||null==d.template||0==d.template.length)return a(ErrorCode.None,null);var l=d.template.length;if(1==l)return a(ErrorCode.None,d.template[0]);var h=function(f){if(f>=l)return a(ErrorCode.None,d.template[l-1]);var e=d.template[f];r(b,e.match||("string"==typeof e.article?e.article:e.article.select),function(b){if(b)return a(ErrorCode.None,e,f);h(++f)})};
h(0)},r=function(b,d,a){if(null==d||"body"==d.toLowerCase())return a(!0);"string"==typeof d&&(d=[d]);var l=d.length,h=function(f){if(f>=l)return a(!1);Utils.SendMessage(b,MessageCommand.CheckArticle,d[f],null,function(b){if(b)return a(!0);h(f+1)})};h(0)},A=function(b){b.find("[tts-id]").each(function(){var b=$(this),a=b.attr("tts-id"),h=b.text().trim();null==a||String.isNullOrEmpty(h)||(b.prepend(Utils.BuildTtsId(a)),b.find("[tts-id]").removeAttr("tts-id"))})},x=function(b){b=$("<div>").append(b);
A(b);return Utils.ReduceWhitespaces(b.text(),!0)},v=function(b,d,a,f){var l={};d=E(b,d,f.article,!0);A(d);var e=h(b,d,f.title);String.isNullOrEmpty(e)&&(e=Utils.GetMessage("text_article_no_title"));l.title=e;"string"==typeof f.author&&(f.author={select:f.author});null==f.author.join&&(f.author.join=", ");e=h(b,d,f.author);e=String.isNullOrEmpty(e)?a:Utils.ToUpperCaseFirstLetters(e).replace(" And "," and ");e=Utils.RemovePrefix(e,["by","por"]);l.author=Utils.Trim(e,"[,|;|:|-]");e=h(b,d,f.time);String.isNullOrEmpty(e)&&
(e=Utils.GetMessage("text_article_no_date"));e=Utils.RemovePrefix(e,["published","updated","posted","on","at"]);e.substring(0,10);e=e.split("\n")[0].replace(/(\d+?)m/i,"$1 minute").replace(/$1 minutes/i,"1 minute").replace(/(\d+?)h/i,"$1 hours").replace(/$1 hours/i,"1 hour");a=/([^T]+T\d+:\d+:\d+)/.exec(e);null!=a&&1<a.length&&!String.isNullOrEmpty(a[1])&&(e=a[1].replace("T"," "),e.endsWith(" 00:00:00")&&(e=e.substring(0,e.length-9)));l.time=Utils.Trim(e,"[,|;|-|:]");d.find("script").remove();d=E(b,
d,f.body);1<d.length&&(d=$("<div>").append(d));1==d.length&&(d=$(d[0].outerHTML.replace(/\n/g," ")));d.find("p,div,h0,h1,h2,h3,h4,h5,h6,li").append("\n");d.find("br").replaceWith("\n");l.body=Utils.ReduceWhitespaces(d.text(),!0);return l},E=function(b,d,a,h){"string"==typeof a&&(a={select:a});if(null!=a["pre-remove"]||null!=a.remove)d=d.clone(),1<d.length&&(d=$("<div>").append(d));null!=a["pre-remove"]&&d.find(a["pre-remove"]).remove();if(1!=h&&null!=a.select){h=a.select;"string"==typeof h&&(h=[h]);
for(var f=d,l=0,e=h.length;l<e&&!(d=D(b,f,h[l]),0<d.length);l++);}b=a["filter-node-types"];if(null!=b){var k=b.split(",");d=d.contents().filter(function(b,d){return 0<=k.indexOf(d.nodeType.toString())})}null!=a.remove&&(1<d.length&&(d=$("<div/>").append(d)),d.find(a.remove).remove());return d.append(" ")},C=function(b,d){var a=null!=d.split;b=Utils.ReduceWhitespaces(b,a);if(null!=d.split){var h=d.split.lastIndexOf(":"),f=0>h?d.split:d.split.substring(0,h),e=0>h?"":d.split.substring(h+1).trim();e=
""==e?["0"]:e.split(",");var k=b.split(f);b=[];h=0;for(var t=e.length;h<t;h++){var p=parseInt(e[h]);0<=p&&p<k.length&&b.push(k[p])}b=b.join(f)}d=d.match;if(!String.isNullOrEmpty(b)&&null!=d)for("string"==typeof d&&(d=[d]),h=0,t=d.length;h<t;h++)if(f=(new RegExp(d[h],"i")).exec(b),null!=f&&1<f.length&&!String.isNullOrEmpty(f[1])){b=f[1];break}return Utils.ReduceWhitespaces(b,a)},F=function(b,d){b=String.isNullOrEmpty(d.attr)?b.text():b.attr(d.attr);if(!String.isNullOrEmpty(d.json)){b=b.replace(",]",
"]");var a=Utils.ParseJson(b);$.each(d.json.split("."),function(b,d){null!=a&&(a=a[d])});b=null==a?"":a.toString()}return b},D=function(b,d,a){var h=a.trim().toLowerCase();0<=h.indexOf("[")&&(h=h.split("[")[0]);0<=h.indexOf(":")&&(h=h.split(":")[0]);return 1==Consts.HeadTags[h]?b.find(a):d.find(a)},h=function(b,d,a,h){"string"==typeof a&&(a={select:a});if(String.isNullOrEmpty(a.select))return a.default||"";d=E(b,d,a);d.find("br").replaceWith("\n");"string"==typeof a.select&&a.select.toLowerCase().startsWith("meta[")&&
null==a.attr&&(a.attr="content");b="";if(String.isNullOrEmpty(a.join))b=F(d,a),b=C(b,a);else{var f=[];$.each(d,function(b,d){b=F($(d),a);b=C(b,a).trim();String.isNullOrEmpty(b)||f.push(b)});b=Utils.ReduceWhitespaces(f.join(a.join),!1)}b=(b||"").trim();String.isNullOrEmpty(b)&&(b=a.default||"");return b},t=function(b,a,h){var d=p(b);b=k(b);for(var f=null,e=0,l=a.template.length;e<l&&!(f=a.template[e],0<d.find(f.match||("string"==typeof f.article?f.article:f.article.select)).length);e++);a=v(d,b,a.host,
f);h(a)};return{constructor:Extractor$,GetSelection:function(){return a.apply(this,arguments)},GetParagraph:function(){return e.apply(this,arguments)},GetArticle:function(){return f.apply(this,arguments)},GetArticleBySite:function(){return q.apply(this,arguments)}}}();var Extractor=new Extractor$;function Tts$(){}
Tts$.prototype=function(){var a=null,e=0,f=null,n=function(a,f){var h="";$.each(a.blocks,function(a,b){if(255<=h.length)return!1;h+=" "+b.text});Utils.DetectLanguage(h,f)},q=function(a,f,h){Db.GetBook(a,function(e){null!=e&&(e.position=f,e.timestamp=(new Date).getTime(),Db.SaveBook(a,e,h))})},p=function(a,f){if(null!=a.voice&&"default"!=a.voice)return f(a.voice);var h=function(a){B(a,function(b){return f(b.voiceName)})};if(null!=a.language&&""!=a.language)return h(a.language);n(a,function(f){a.language=
f||"en";a.voice="default";Db.SaveBook(a.bookId,a);h(f)})},k=function(a){var f=[];$.each(Utils.BreakLineToBlocks(a.text,Settings.Data.maxBlockSize),function(b,a){f.push({text:a})});if(a.pageEnd&&0<f.length){var h=f.first(),e=f.last();null==a.partialPos?e.nextPageAtEnd=!0:(a=6E4*a.text.substring(0,a.partialPos).split(" ").length/240/Settings.Data.ttsRate,h.nextPageAtStart=!0,h.nextPageDelay=a,e.nextPageCheck=!0)}return f},z=function(a,f){u();Utils.DetectLanguage(f,function(a){B("en",function(a){chrome.tts.speak(f,
{volume:Settings.Data.ttsVolume,rate:Settings.Data.ttsRate,voiceName:a.voiceName})})})},w=function(n,v){Utils.GetTabInfo(n,function(h,t,b,d){e=t;a=v.bookId;p(v,function(b){$.each(v.blocks,function(a,d){a<v.start||$.each(k(d),function(a,h){chrome.tts.speak(h.text,{enqueue:!0,volume:Settings.Data.ttsVolume,rate:Settings.Data.ttsRate,voiceName:b,onEvent:function(b){switch(b.type){case "start":Utils.SendMessage(e,MessageCommand.Highlight,{position:d.position,ttsHighlight:Settings.Data.ttsHighlight});
q(v.bookId,d.position);h.nextPageAtStart&&(f=Utils.SetTimeout(f,h.nextPageDelay,function(){f=null;x(!0)}));break;case "end":h.nextPageAtEnd&&x(!1),h.nextPageCheck&&f&&(f=Utils.ClearTimeout(f),x(!0))}}})})})})})},u=function(){f=Utils.ClearTimeout(f);null!=a&&(a=null,Utils.SendMessage(e,MessageCommand.UpdateReadingStatus,{isReading:!1}));chrome.tts.stop()},B=function(a,f){String.isNullOrEmpty(a)&&(a="en");var h=a.split("-")[0],e=Settings.Data.VoiceTemplates[h];null==e&&(e=new VoiceTemplate(h),e.template=
Settings.Data.VoiceTemplates.en.template);A(function(b){b=b[a]||b.en;for(var d=e.voice,h=0,k=b.length;h<k;h++){var p=b[h];if(p.voiceName==d)return f(p)}return 0<b.length?f(b[0]):f({voiceName:"native"})})},r=function(a){chrome.tts.getVoices(a)},A=function(a){r(function(f){var h=[];$.each(f,function(){if(!String.isNullOrEmpty(this.lang)){var b=this.lang.split("-")[0],a=h[b];null==a&&(a=h[b]=[]);a.push(this)}});f=h.en;for(var e=0,b=f.length;e<b;e++){var d=f[e];if("Google US English"==d.voiceName){f.splice(e,
1);f.splice(0,0,d);break}}a(h)})},x=function(a){Utils.SendMessage(e,MessageCommand.NextPage,{resumeWhenBookReady:!0,skipFirstBlock:a})},v=function(a){chrome.tts.isSpeaking(a)},E=function(){return a},C=function(a){};return{Play:function(){return Play.apply(this,arguments)},Pause:function(){return Pause.apply(this,arguments)},Resume:function(){return Resume.apply(this,arguments)},Stop:function(){return u.apply(this,arguments)},ReadBook:function(){return w.apply(this,arguments)},GetVoices:function(){return r.apply(this,
arguments)},GetVoiceGroups:function(){return A.apply(this,arguments)},IsReading:function(){return v.apply(this,arguments)},GetReadingBookId:function(){return E.apply(this,arguments)},RegisterEvent:function(){return C.apply(this,arguments)},Speak:function(){return z.apply(this,arguments)},constructor:Tts$}}();var Tts=new Tts$;function Feedback$(){}
Feedback$.prototype=function(){var a=function(a,n){Repo.GetSite(a,!0,function(a,f){if(a==ErrorCode.None&&null!=f&&null!=f.id&&0!=f.id){var k=e(n);Service.PutSiteIssues(f.id,k,function(a,e){a==ErrorCode.None&&(a=!1,f.issues!=k&&(f.issues=k,a=!0),0!=k&&(f.cachedTime=0,a=!0),a&&Repo.SaveSite(f))})}})},e=function(a){var f=IssueType.None;if(null==a)f+=IssueType.Missing;else if(null==a.blocks||0==a.blocks.length)f+=IssueType.Body;return f};return{constructor:Feedback$,PutBookIssues:function(){return a.apply(this,arguments)}}}();
var Feedback=new Feedback$;function BookData(){this.bookId="";this.position=0;this.cover="";this.timestamp=0}function SiteTemplate(){this.id=0;this.host="";this.template=[new PageTemplate];this.createdTime;this.updatedTime;this.cachedTime;this.lastModified;this.official=this.published=this.verified=!1;this.issues=-1;this.visible=!1}function ArticleData(){this.language="en";this.host;this.title;this.author;this.time;this.body}function PageLanuageData(){this.default="en";this.auto=!1}
function PageTemplate(){this.example="";this.language="en";this.article="body";this.title="title";this.author=".author:first";this.time="time:first";this.body={"pre-remove":"figure,aside,header,footer",select:"p",remove:"div"}}
function SettingsData(){this.activeLanguageCode=this.activeTab="";this.theme=this.username=this.userGuid=null;this.maxBlockSize=150;this.ttsRate=this.ttsVolume=1;this.ttsRateGap=.25;this.ttsScroll=this.ttsHighlight=!0;this.VoiceTemplates={};this.translationLanguage="en";this.translationPopupEnabled=!0;this.translationPopupKey=TranslationPopupKey.None}function VoiceTemplate(a){this.code=void 0===a?"en":a;this.voice="default";this.example=this.template=null}
function TemplateData(){this.attr=this.match=this.remove=this.select=this.default=""};var Config={ConfigUrl:"https://sites.google.com/site/ireadwebpage/config.json",UserApiKey:"E38FC4F8-0B6F-4B4B-B378-8A760A648131",LicenseUrl:"https://www.googleapis.com/chromewebstore/v1.1/userlicenses/",RevokeUrl:"https://accounts.google.com/o/oauth2/revoke?token=",AppStoreUrl:"https://chrome.google.com/webstore/detail/tts-scribd-reader/lnaecppekphilbjkgfgbjhjiokkpfgeh",DefaultServiceUrl:"http://ec2-35-165-140-185.us-west-2.compute.amazonaws.com/v1/"};function Service$(){}
Service$.prototype=function(){var a=null,e=function(a,f,e){a="sites/"+a;var k=u();k["If-Modified-Since"]=f;r("GET",a,k,null,e)},f=function(a,f,e){var k=u();k["If-Modified-Since"]=f;r("GET","sites/host/"+a+"/primary",k,null,e)},n=function(a,f){var e=u();return r("GET","sites/host/"+a,e,null,f)},q=function(a,f,e){var k=u();f={template:JSON.stringify(f)};r("PUT","sites/host/"+a+"/template",k,f,e)},p=function(a,f,e){var k=u();r("PUT","sites/"+a+"/issues/"+f,k,null,e)},k=function(a,f,e){var k=u();a="users/guid/"+
w()+"?name="+encodeURIComponent(a)+"&email="+encodeURIComponent(f);r("PUT",a,k,null,e)},z=function(a,f){var e=u();r("POST","issues",e,a,f)},w=function(){Settings.ResetData();return Settings.Data.userGuid},u=function(){var f=Config.UserApiKey,e=w();null==a&&(a=Utils.GetManifest().version);return{"X-API-KEY":f,"X-API-USER":e,"X-APP-VER":a}},B=function(a,f,e){if(!a)return e(ErrorCode.None,null);chrome.identity.getAuthToken({interactive:!1},function(a){return chrome.runtime.lastError?e(ErrorCode.SystemError,
chrome.runtime.lastError.message):f?chrome.identity.removeCachedAuthToken({token:a},function(){chrome.identity.getAuthToken({interactive:!1},function(a){return chrome.runtime.lastError?e(ErrorCode.SystemError,chrome.runtime.lastError.message):e(ErrorCode.None,a)})}):e(ErrorCode.None,a)})},r=function(a,f,e,k,p,n,h){B(void 0===n?!1:n,void 0===h?!1:h,function(h,b){if(h!=ErrorCode.None)return p(h,b);e=e||{};null!=b&&(e.Authorization=Utils.RsaEncryption(Consts.RsaPublicKey,"Bearer "+b));A(a,f,e,k,function(b,
h,t){if(b!=ErrorCode.None)return p(b,h);if(200==t.status||304==t.status||404==t.status)return p(ErrorCode.None,h,t);if(401!=t.status)return p(ErrorCode.SystemError,h,t);b=JSON.parse(t.responseText);return b.code==ErrorCode.ErrorLicenseTokenRequired?r(a,f,e,k,p,!0,!1):b.code==ErrorCode.ErrorLicenseTokenExpired?r(a,f,e,k,p,!0,!0):p(b.code,b.message)})})},A=function(a,f,e,k,p){Utils.Background().SettingsGetServiceUrl(!1,function(n,h){if(n!=ErrorCode.None)return p(n,h);url=h+f;Utils.UrlRequest(a,url,
e,k,function(h,b,d){if(0!=d.status&&503!=d.status)return p(ErrorCode.None,b,d);Utils.Background().SettingsGetServiceUrl(!0,function(d,h){if(d!=ErrorCode.None)return p(d,h);url=h+f;Utils.UrlRequest(a,url,e,b,function(b,a,d){return p(ErrorCode.None,a,d)})})})})};return{constructor:Service$,GetSiteById:function(){return e.apply(this,arguments)},GetPrimarySite:function(){return f.apply(this,arguments)},GetSitesByHost:function(){return n.apply(this,arguments)},PutSiteTemplate:function(){return q.apply(this,
arguments)},PutSiteIssues:function(){return p.apply(this,arguments)},UpdateUserInfo:function(){return k.apply(this,arguments)},SubmitIssue:function(){return z.apply(this,arguments)}}}();var Service=new Service$;function Settings$(){}
Settings$.prototype=function(){var a=null,e=function(){var e=!1,k=Utils.Background().SettingsGetData();String.isNullOrEmpty(k.theme)&&(k.theme="cupertino",e=!0);null==k.voice&&(k.voice="native",e=!0);null==k.activeTab&&(k.activeTab=0,e=!0);null==k.maxBlockSize&&(k.maxBlockSize=120,e=!0);null==k.ttsVolume&&(k.ttsVolume=1,e=!0);null==k.ttsRate&&(k.ttsRate=1,e=!0);null==k.ttsRateGap&&(k.ttsRateGap=.25,e=!0);null==k.ttsHighlight&&(e=k.ttsHighlight=!0);null==k.ttsScroll&&(e=k.ttsScroll=!0);null==k.VoiceTemplates&&
(k.VoiceTemplates=[],e=!0);null==k.VoiceTemplates.en&&(k.VoiceTemplates.en=new VoiceTemplate("en"),e=!0);String.isNullOrEmpty(k.translationLanguage)&&(k.translationLanguage=(window.navigator.language||"").split("-")[0],e=!0);null==k.translationPopupEnabled&&(k.translationPopupEnabled=!0,k.translationPopupKey=TranslationPopupKey.None,e=!0);null==k.krBoxPos&&(k.krBoxPos={top:"60px"},e=!0);e&&f();a=k;q()},f=function(){Utils.Background().SettingsSaveData()},n=function(e){if(e&&e.id&&""!=e.id)return e.extensionId=
Config.AppStoreUrl.split("/").last(),e=JSON.stringify(e),a.userGuid="sru"+(new Hashes.SHA1).hex(e),f();e=(a.userGuid||"").trim();if(""==e||"null"==e||"undefined"==e)return e=new Uint32Array(4),window.crypto.getRandomValues(e),e=JSON.stringify(e),a.userGuid="srg"+(new Hashes.SHA1).hex(e),f()},q=function(){chrome.identity.getProfileUserInfo(n);chrome.identity.onSignInChanged.addListener(function(a,e){chrome.identity.getProfileUserInfo(n)})};return{constructor:Settings$,Data:null,Init:function(){e.apply(this,
arguments);this.Data=a},Save:function(){return f.apply(this,arguments)},ResetData:function(){return n.apply(this,arguments)}}}();var Settings=new Settings$;$(document).ready(function(){Background.Run()});function Background$(){}
Background$.prototype=function(){var a=null,e=Config.DefaultServiceUrl,f={},n=function(){Repo.GetSettings(function(e){null==e&&(e=new SettingsData);a=e;Settings.Init();chrome.commands.onCommand.addListener(r);chrome.extension.onRequest.addListener(B);Tts.RegisterEvent(A)})},q=function(a,e,b){var d={ttsHighlight:Settings.Data.ttsHighlight,isReading:Tts.GetReadingBookId()==e};Db.GetBook(e,function(a){null!=a&&(d.exists=!0,d.position=a.position);b(d)})},p=function(a,e){if(null==a)return e(a);Db.GetBook(a.bookId,
function(b){null==b&&(b=new BookData,b.bookId=a.bookId);null!=a.title&&(b.title=a.title);null!=a.authors&&(b.authors=a.authors);null!=a.position&&(b.position=a.position);null!=a.progress&&(b.progress=a.progress);null!=a.cover&&(b.cover=a.cover);null!=a.url&&(b.url=a.url);b.timestamp=(new Date).getTime();Db.SaveBook(a.bookId,b);a.language=b.language;a.voice=b.voice;e(a)})},k=function(a,e){var b={styleUrl:Utils.ExtGetUrl("lib/jquery-ui/themes/"+Settings.Data.theme+"/jquery-ui.css"),themeBackgroundColor:ThemeBackgroundColors[Settings.Data.theme],
krBoxPos:Settings.Data.krBoxPos,readingBookId:Tts.GetReadingBookId()},d=f[a];null!=d&&(b.command=d,f[a]=null);e(b)},z=function(a,e,b){Repo.GetSite(Consts.ScribdHost,e,function(d,f){if(d!=ErrorCode.None)return x({code:d,message:f,sender:this,tabId:a},function(d){d&&z(a,e,b)});d=null==f||null==f.template||0==f.template.length?null:f.template[0].scribd;"undefined"!=typeof getSiteScribd&&(Repo.RemoveSite(Consts.ScribdHost),d=getSiteScribd());b(d)})},w=function(a,e){a=!1;null!=e.krBoxPos&&(Settings.Data.krBoxPos=
e.krBoxPos,a=!0);a&&Settings.Save()},u=function(a,e){delete e.command;delete e.cover;var b=JSON.stringify(e),d=Utils.GetMessage("report_issue_no_text",b);Utils.SendMessage(a,MessageCommand.Confirm,d,null,function(a){a&&Service.SubmitIssue({siteId:0,url:e.url,note:b,issues:IssueType.Wrong|IssueType.Body},function(a,b){})});Feedback.PutBookIssues(Consts.ScribdHost,{})},B=function(a,e,b){switch(a.command){case RequestCommand.GetSettings:k(e.tab.id,b);break;case RequestCommand.GetTemplate:z(e.tab.id,
a.localOnly,b);break;case RequestCommand.SetSettings:w(e.tab.id,a);b({});break;case RequestCommand.GetBookStatus:q(e.tab.id,a.bookId,b);break;case RequestCommand.SetBookPos:p(a,function(a){b({})});break;case RequestCommand.Read:1!=a.enqueue&&Tts.Stop();a.feedback&&Feedback.PutBookIssues(Consts.ScribdHost,a);p(a,function(a){Tts.ReadBook(e.tab,a);b({})});break;case RequestCommand.Stop:Tts.Stop();b({});break;case RequestCommand.Speak:Tts.Speak(e.tab,a.text),b({});case RequestCommand.ReportIssue:u(e.tab.id,
a);b({});break;default:b({})}},r=function(a){switch(a){case ShortcutCommands.Read:Utils.SendMessage(tab.id,MessageCommand.Read);break;case ShortcutCommands.Stop:Utils.SendMessage(tab.id,MessageCommand.Stop)}},A=function(a,e){switch(a){case Consts.TtsEvents.started:onReadStarted(e);break;case Consts.TtsEvents.paused:onReadPaused(e);break;case Consts.TtsEvents.resumed:onReadResumed(e);break;case Consts.TtsEvents.ended:onReadEnded(e);break;case Consts.TtsEvents.error:x(e)}},x=function(a,e){if(null!=
a&&a.sender==this){var b="";switch(a.code){case ErrorCode.NoText:case ErrorCode.NoDocument:case ErrorCode.ParseArticleError:return Utils.SendMessage(a.tabId,MessageCommand.Alert,a.message);case ErrorCode.NoTemplate:Utils.SendMessage(a.tabId,MessageCommand.Alert,Utils.GetMessage("error_article_no_template"));break;case ErrorCode.ErrorLicenseExpired:case ErrorCode.ErrorLicenseNone:a.code==ErrorCode.ErrorLicenseNone?b=Utils.GetMessage("issue_no_license"):a.code==ErrorCode.ErrorLicenseExpired&&(b=Utils.GetMessage("issue_license_is_expired"));
b=Utils.GetMessage("confirm_app_subscription",b);Utils.SendMessage(a.tabId,MessageCommand.Confirm,b,null,function(a){a&&Utils.OpenNewTab(Config.AppStoreUrl)});break;case ErrorCode.SystemError:v(a.tabId,a.message,e)}}},v=function(a,e,b){var d=function(d){chrome.identity.getAuthToken({interactive:d},function(d){chrome.runtime.lastError?v(a,chrome.runtime.lastError.message):b&&b(!0)})};switch(e){case "The user is not signed in.":issue=Utils.GetMessage("issue_user_not_sign_in");e=Utils.GetMessage("confirm_sign_in_to_chrome",
issue);Utils.SendMessage(a,MessageCommand.Confirm,e,null,function(a){a&&d(!0)});break;case "OAuth2 not granted or revoked.":issue=Utils.GetMessage("issue_oauth2_not_granted");e=Utils.GetMessage("confirm_granted_oauth2",issue);Utils.SendMessage(a,MessageCommand.Confirm,e,null,function(a){a&&d(!0)});break;case "Authorization page could not be loaded.":issue=Utils.GetMessage("issue_auth_page_not_loaded");e=Utils.GetMessage("confirm_granted_oauth2",issue);Utils.SendMessage(a,MessageCommand.Confirm,e,
null,function(a){a&&(d(!1),d(!0))});break;default:e=Utils.GetMessage("warning_system_error",e),Utils.SendMessage(a,MessageCommand.Alert,e)}},E=function(){return a},C=function(){Repo.SaveSettings(a)},F=function(a,f){if(null!=e&&1!=a)return f(ErrorCode.None,e);Utils.UrlGet(Config.ConfigUrl,null,function(a,d){if(!a)return f(ErrorCode.SystemError,d);e=d.ServiceUrl;return f(ErrorCode.None,e)})},D=function(a,e,b){f[a]={event:e,data:b}};return{Run:function(){return n.apply(this,arguments)},SettingsGetData:function(){return E.apply(this,
arguments)},SettingsSaveData:function(){return C.apply(this,arguments)},SettingsGetServiceUrl:function(){return F.apply(this,arguments)},UpdateTranslationMenus:function(){return UpdateTranslationMenus.apply(this,arguments)},SendPendingCommand:function(){return D.apply(this,arguments)},constructor:Background$}}();var Background=new Background$;
