var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,e,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,c){b!=Array.prototype&&b!=Object.prototype&&(b[e]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,e,c,g){if(e){c=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var d=b[g];d in c||(c[d]={});c=c[d]}b=b[b.length-1];g=c[b];e=e(g);e!=g&&null!=e&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(b,c){var e=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===c&&(c=e.length);c=Math.max(0,Math.min(c|0,e.length));for(var d=b.length;0<d&&0<c;)if(e[--c]!=b[--d])return!1;return 0>=d}},"es6","es3");$jscomp.findInternal=function(b,e,c){b instanceof String&&(b=String(b));for(var g=b.length,d=0;d<g;d++){var h=b[d];if(e.call(c,h,d,b))return{i:d,v:h}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");var MessageCommand={OpenLibrary:1,Highlight:2,NextPage:3,Alert:4,Confirm:5,Style:6,Read:7,Stop:8,UpdateReadingStatus:9},RequestCommand={GetSettings:1,GetTemplate:2,GetBookStatus:3,SetSettings:4,SetBookPos:5,Play:6,Stop:7,Speak:8,ReportIssue:9},IssueType={None:0,Missing:1,Wrong:2,Others:4,Title:16,Author:32,Time:64,Body:128,Language:256};var Consts={StyleUrlId:"tts_style",TtsIdFirst:"tts_first",TtsIdLast:"tts_last",AbbrWords:{"u.s.":!0,"a.":!0,"n.":!0,"sen.":!0,"dr.":!0,"esq.":!0,"jon.":!0,"jr.":!0,"mr.":!0,"mrs.":!0,"ms.":!0,"messrs.":!0,"mmes.":!0,"msgr.":!0,"prof.":!0,"rev.":!0,"rt.":!0,"sr.":!0,"st.":!0,"jan.":!0,"feb.":!0,"mar.":!0,"apr.":!0,"may.":!0,"jun.":!0,"jul.":!0,"aug.":!0,"spt.":!0,"oct.":!0,"nov.":!0,"dec.":!0,"co.":!0,"a.m.":!0,"p.m.":!0,"i.e.":!0,"no.":!0}},Visible={Hidden:0,Partial:1,Full:2};String.prototype.in=String.prototype.in||function(){for(var b=this.toString(),e=0,c=arguments.length;e<c;e++)if(arguments[e]==b)return!0;return!1};Array.prototype.last=Array.prototype.last||function(){return 0<this.length?this[this.length-1]:null};Array.prototype.first=Array.prototype.first||function(){return 0<this.length?this[0]:null};function Utils$(){}
Utils$.prototype=function(){var b=function(b){console.log.apply(this,$.merge([(new Date).toISOString()+":"],arguments))},e=function(b){console.error.apply(this,arguments)},c=function(b,r,c){null!=b&&0!=b&&clearTimeout(b);return setTimeout(c,r)},g=function(b){clearTimeout(b);return null},d=function(b,c,d){c=c||{};c.command=b;chrome.extension.sendRequest(c,d||function(){})},h=function(b,c){for(var d=0,n=c.length;d<n;d++)if(b.endsWith(c[d]))return!0;return!1},k=function(b,c,d){d=d||document;null!=c&&
$(d).find("#"+c).remove();d=d.getElementsByTagName("head")[0];$("<link>",{id:c,rel:"stylesheet",type:"text/css",href:b}).appendTo(d)},y=function(b){var c=b.parentNode;$.each($.makeArray(b.childNodes),function(d,n){c.insertBefore(n,b)});c.removeChild(b)},z=function(b,c){if(null!=b&&""!=b){if(null==c)return localStorage.removeItem(b);localStorage.setItem(b,JSON.stringify(c))}},t=function(b){b=localStorage.getItem(b);return null==b||""==b?null:JSON.parse(b)},p=function(){return(new Date).getTime()},
u=function(b){var c={};$.each(b.split(";"),function(){var b=this.split(":");switch(b.length){case 1:c[b[0]]="";break;case 2:c[b[0]]=b[1]}});return c},v=function(b,c,d){return{left:b.left+c,top:b.top+d,right:b.right+c,bottom:b.bottom+d}},B=function(b,c,d,e){return{left:b,top:c,right:d,bottom:e}};return{Log:function(){return b.apply(this,arguments)},LogError:function(){return e.apply(this,arguments)},SetTimeout:function(){return c.apply(this,arguments)},ClearTimeout:function(){return g.apply(this,arguments)},
SendRequest:function(){return d.apply(this,arguments)},EndsWith:function(){return h.apply(this,arguments)},AppendStyleUrl:function(){return k.apply(this,arguments)},Unwrap:function(){return y.apply(this,arguments)},SaveToStorage:function(){return z.apply(this,arguments)},LoadFromStorage:function(){return t.apply(this,arguments)},GetTimestamp:function(){return p.apply(this,arguments)},ParseStyle:function(){return u.apply(this,arguments)},OffsetRect:function(){return v.apply(this,arguments)},MakeRect:function(){return B.apply(this,
arguments)},constructor:Utils$}}();var Utils=new Utils$;function Tts$(){}
Tts$.prototype=function(){var b=!1,e=!1,c=0,g=null,d=[],h=-1,k=!1,y=null,z="#eee",t=!0,p=null,u=null,v=null,B=null,n=null,r=null,I=null,J=0,na=function(){chrome.runtime.onMessage.addListener(K);Utils.SendRequest(RequestCommand.GetSettings,null,function(a){if(null==a)return Utils.LogError("Failed to get settings from extension");u=a.krBoxPos;y=a.styleUrl;z=a.themeBackgroundColor;var b=a.readingBookId;C();k=b==n;L();D();b=$("<div class='kr-box ui-widget-content ui-corner-all'/>");var f=$("<div class='head'/>"),
c=$("<div class='buttons'/>"),d=$("<span class='title'>TTS Scribd Reader</span>").hide(),e=q("expand","ui-icon-caret-1-e").click(M),h=q("shink","ui-icon-caret-1-w").hide().click(N),g=q("setting","ui-icon-gear").click(ba).hide(),p=q("prevPage","ui-icon-seek-first").click(ca),r=q("prevBlock","ui-icon-seek-prev").click(da),t=q("play","ui-icon-play").css("display","inline-block").click(ea),v=q("stop","ui-icon-stop").css("display","none").click(O),w=q("nextBlock","ui-icon-seek-next").click(fa),x=q("netxtPage",
"ui-icon-seek-end").click(P);f.append(e).append(h).append(d).append(g).appendTo(b);c.hide().append(p).append(r).append(t).append(v).append(w).append(x).appendTo(b);b.appendTo(document.body);b.find("button").button();f=u;null!=f.top?b.css("top",f.top):null!=f.bottom&&b.css("bottom",f.bottom);b.mousedown(ha).mouseenter(ia).mouseleave(ja);$(window).mousemove(ka).mouseup(la).resize(ma);null!=a.command&&K(a.command,null,null)})},Q=function(a,b){if(null!=v)return b(v);Utils.SendRequest(RequestCommand.GetTemplate,
{localOnly:a},function(a){if(null==a)return Utils.LogError("Failed to get template from extension");v=a;b(v)})},L=function(){var a=$("div.page_counter");if(""==a.text().trim())return Utils.SetTimeout(0,100,L);var b=0;(new MutationObserver(function(a){b=Utils.SetTimeout(b,0,R)})).observe(a[0],{subtree:!0,attributes:!0,childList:!0,characterData:!0});b=Utils.SetTimeout(b,0,R)},q=function(a,b){return $("<button class='"+a+"'><i class='ui-icon "+b+"'/></button>")},M=function(a){a=$(".kr-box");a.find(".expand").hide();
a.find(".shink").show();a.find(".title,.buttons").show("slide",null,300)},N=function(a){a=$(".kr-box");a.find(".expand").show();a.find(".shink").hide();a.find(".title,.buttons").hide("slide",null,300)},ba=function(a){},fa=function(a){if(h>=d.length-1)return w(Consts.TtsIdFirst,function(){E()});++h;A(10);k?x(!1):w(F())},da=function(a){if(0>=h)return w(Consts.TtsIdLast,function(){S()});--h;A(10);k?x(!1):w(F())},T=function(){var a=$(".kr-box"),b=a.position().top,f=a.height(),c={};b+f>window.innerHeight?
(a.css("top","").css("bottom","0px"),c.bottom="0px"):(0>b&&a.css("top","0px").css("bottom",""),c.top=a.css("top"));Utils.SendRequest(RequestCommand.SetSettings,{krBoxPos:c})},ma=function(a){T();B=null},ha=function(a){p=a.pageY;a=$(".kr-box").offset();null!=a&&(u.top=a.top-$(document).scrollTop())},la=function(a){p=null},ka=function(a){null!=p&&(u.top+=a.pageY-p,p=a.pageY,$(".kr-box").css("bottom","").css("top",u.top),T(),a.preventDefault())},ia=function(a){c=Utils.ClearTimeout(c);M(a);$(".kr-box").addClass("kr-box-active",
400)},ja=function(a){c=Utils.SetTimeout(c,1E3,function(){N(a);$(".kr-box").removeClass("kr-box-active",400)})},S=function(a){$("div.icon-ic_back_arrow").trigger("click")},E=function(a){$("div.icon-ic_right_arrow").trigger("click")},ca=function(a){w(Consts.TtsIdFirst,function(){S()})},P=function(a){w(Consts.TtsIdFirst,function(){E()})},G=function(){var a=$(".kr-box");a.find(".play").css("display",k?"none":"inline-block");a.find(".stop").css("display",k?"inline-block":"none")},ea=function(a){Q(!1,function(a){null!=
a&&U(function(){return x(!1,!0)})})},O=function(a){Utils.SendRequest(RequestCommand.Stop,{},function(){k=!1;G()})},F=function(){return 0<=h&&h<d.length?d[h].position:null},A=function(a,b){var f=F(),c=$(".kr-highlight");f=$('[tts-id="'+f+'"]');1!=b&&t&&c[0]==f[0]||(c.removeClass("kr-highlight",a).css("background-color",""),t&&f.addClass("kr-highlight",a).css("background-color",z))},D=function(){$(document).find("#"+Consts.StyleUrlId).attr("href")!=y&&Utils.AppendStyleUrl(y,Consts.StyleUrlId,document)},
R=function(){var a=null,c=2;C();var f=n;var d=function(){0<--c||(h=V(a.position),k=a.isReading,t=a.ttsHighlight,D(),A(10),e&&(e=!1,h++),b?(b=!1,x(!0,0==k)):k&&x(!1))};Q(!0,function(a){null!=a&&Utils.SetTimeout(0,100,function(){U(d)})});Utils.SendRequest(RequestCommand.GetBookStatus,{bookId:f},function(b){if(null==b)return Utils.LogError("Failed to get book status from extension");a=b;d()})},C=function(){null==n&&$("script").each(function(a,b){a=b.innerText;b=a.indexOf("Scribd.current_doc = ");if(!(0>
b))return a=a.substring(b+21).trim(),a.endsWith(";")&&(a=a.substring(0,a.length-1)),data=JSON.parse(a),n=data.id.toString(),r=data.title,I=data.author_name,""==(r||"")&&(r=$("h1:first").text()),!1})},H=function(a){C();a={position:a};var b=location.host,c=location.origin,d=$(".cover-2d-img:first>img").attr("src");a.bookId=b.split(".")[0];a.url=location.href;a.cover=""+c+d;a.bookId=n;a.title=r;a.authors=I;a.progress=$("div.percentage_read").text().split(" ")[0];a.pageId=$("div.page_counter").text();
a.cover=$("img.document_cover").attr("src");""==(a.pageId||"")&&(a.pageId=$(".page_input").val()+" "+$(".total_pages span:last").text());return a},x=function(a,c){if(0==d.length){if(5<++J)return Utils.SendRequest(RequestCommand.ReportIssue,H());b=!0;return E()}J=0;var f=0>h?0:h,l=H(d[f].position);l.enqueue=a;l.blocks=d;l.start=f;l.feedback=c;Utils.SendRequest(RequestCommand.Read,l,function(){k=!0;G()})},w=function(a,b){a=H(a);Utils.SendRequest(RequestCommand.SetBookPos,a,b)},W=function(a){for(var b=
/\. |\.'|\."|\.\u201d|\.$|\? |\?'|\?"|\?\u201d|\?$|! |!'|!"|!\u201d|!$|\u3002|\u3002'|\u3002"|\u3002\u201d/g,c=0,d={items:[],isBlockDone:!1};m=b.exec(a);){var e=m[0].length,h=m.index+e,g=a.substring(c,h);if(!oa(g)&&(d.items.push(g),c=h,0==e))break}d.isBlockDone=0<d.items.length;c<a.length&&(g=a.substring(c,a.length),""!=g.trim()&&(d.isBlockDone=!1),d.items.push(g));return d},X=function(a){null==a.ttsId&&(a.ttsId=++a.ttsIdIdx,a.dataPos=a.lastDataPos);return a.dataPos+":"+a.ttsId},pa=function(a){var b=
[];$.each(a.nodes,function(a,c){b.push({position:c.ttsId,text:c.text})});a=b.last();null!=a&&(a.pageEnd=!0);return b},V=function(a){var b=d.length;switch(a){case Consts.TtsIdFirst:break;case Consts.TtsIdLast:return b-1;default:for(var c=0;c<b;c++)if(d[c].position==a)return c}return 0},Y=function(a,b,c,d){var f=a.nodes[b];null==f?(a.nodes[b]=f={ttsId:b,text:c},a.nodes.push(f)):f.text+=c;d&&(a.ttsId=null)},Z=function(a,b,c){null==c&&(c=W(b.nodeValue));for(var d=[],f=0,l=c.items.length;f<l;f++){var e=
c.items[f],g=X(a);Y(a,g,e,f!=l-1||c.isBlockDone);e=$("<tts>").text(e).attr("tts-id",g);d.push(e)}$(b).replaceWith(d)},qa=function(a,b){var c=a.childNodes[0],d=c.nodeValue,l=W(d);1<l.items.length?Z(b,c,l):(c=X(b),Y(b,c,d,l.isBlockDone),$(a).attr("tts-id",c))},aa=function(a,b){1==a.childNodes.length&&3==a.childNodes[0].nodeType?qa(a,b):(nodes=$.makeArray(a.childNodes),$.each(nodes,function(a,c){3==c.nodeType?Z(b,c):aa(c,b)}))},ra=function(a){$("tts").each(function(a,b){$(b).replaceWith(b.innerText)});
var b="";$(".text_line").each(function(c,d){c=$(d).attr("data-position");null!=c&&(a.lastDataPos=c,c=c.split(":").slice(0,2).join(":"),c!=b&&(a.ttsId=null,b=c));aa(d,a)})},U=function(a){var b=Utils.GetTimestamp(),c={index:0,dataLocIdx:0,nodes:[],ttsIdIdx:0,ttsId:null};ra(c);var e=c.nodes.length;0<e&&(c.nodes[e-1].pageEnd=!0);g=c.nodes;d=pa(c);Utils.Log("tagBook. Json: "+JSON.stringify(d,null,2));c=d[0];e=d[d.length-2];var h=d[d.length-1];Utils.Log("tagBook: span: "+(Utils.GetTimestamp()-b)+", nodes: "+
g.length+", blocks: "+d.length+", location: "+B+", first: '"+JSON.stringify(c)+"', last2: '"+JSON.stringify(e)+", last: '"+JSON.stringify(h)+"' <<");a()},sa=function(a,b,c,d){var e=a.length;if(0>b||b>=e)return"";for(var f=b;0<=f&&f<e&&d(a[f]);)f+=c?-1:1;return 0>f?c?a.substring(0,b+1):a.substring(b):c?a.substring(f+1,b+1):a.substring(b,f)},oa=function(a){a=a.trim();len=a.length;if(1>=len||"."!=a[len-1])return!1;a=sa(a,len-1,!0,function(a){return"."==a||"a"<=a&&"z">=a||"A"<=a&&"Z">=a});a=a.toLowerCase().trim();
return"."!=a&&Consts.AbbrWords[a]},K=function(a,c,d){c=a.data||{};switch(a.event){case MessageCommand.Alert:return alert(c);case MessageCommand.Confirm:return a=confirm(c),d(a);case MessageCommand.Highlight:t=c.ttsHighlight;null!=c.position&&(h=V(c.position));A(300);break;case MessageCommand.NextPage:b=c.resumeWhenBookReady;e=c.skipFirstBlock;P();break;case MessageCommand.Style:y=c.styleUrl;z=c.themeBackgroundColor;D();$(".kr-box").trigger("mouseenter").trigger("mouseleave");A(300,!0);break;case MessageCommand.Read:k?
x(!1):b=!0;break;case MessageCommand.Stop:O();break;case MessageCommand.UpdateReadingStatus:k=c.isReading,G()}};return{Init:function(){return na.apply(this,arguments)},constructor:Tts$}}();var Tts=new Tts$;$(document).ready(function(){Tts.Init()});
