var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,f,e){if(null==b)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return b+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,e){b!=Array.prototype&&b!=Object.prototype&&(b[f]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,f,e,h){if(f){e=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var n=b[h];n in e||(e[n]={});e=e[n]}b=b[b.length-1];h=e[b];f=f(h);f!=h&&null!=f&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,e){var f=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var n=f.length,p=b.length;e=Math.max(0,Math.min(e|0,f.length));for(var a=0;a<p&&e<n;)if(f[e++]!=b[a++])return!1;return a>=p}},"es6","es3");$jscomp.findInternal=function(b,f,e){b instanceof String&&(b=String(b));for(var h=b.length,n=0;n<h;n++){var p=b[n];if(f.call(e,p,n,b))return{i:n,v:p}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,e){return $jscomp.findInternal(this,b,e).v}},"es6","es3");$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(b,e){var f=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===e&&(e=f.length);e=Math.max(0,Math.min(e|0,f.length));for(var n=b.length;0<n&&0<e;)if(f[--e]!=b[--n])return!1;return 0>=n}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(b){var f=0;return $jscomp.iteratorPrototype(function(){return f<b.length?{done:!1,value:b[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,f){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var e=0,h={next:function(){if(e<b.length){var n=e++;return{value:f(n,b[n]),done:!1}}h.next=function(){return{done:!0,value:void 0}};return h.next()}};h[Symbol.iterator]=function(){return h};return h};
$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");var MessageCommand={OpenLibrary:1,Highlight:2,NextPage:3,Alert:4,Confirm:5,Style:6,Read:7,Stop:8,UpdateReadingStatus:9},RequestCommand={GetSettings:1,GetTemplate:2,GetBookStatus:3,SetSettings:4,SetBookPos:5,Play:6,Stop:7,Speak:8,ReportIssue:9},IssueType={None:0,Missing:1,Wrong:2,Others:4,Title:16,Author:32,Time:64,Body:128,Language:256};var Consts={DefaultUsername:"",SiteExpireInSeconds:604800,TtsEvents:{started:"started",ended:"ended",paused:"paused",resumed:"resumed",data:"data",block:"block",status:"status",error:"error"},TtsCommands:{stop:"stop",play:"play",resume:"resume",pause:"pause",prev:"prev",next:"next",first:"first",last:"last",voice:"voice",seletcion:"selection",paragraph:"paragraph",article:"article"},AbbrWords:{"u.s.":!0,"a.":!0,"n.":!0,"sen.":!0,"dr.":!0,"esq.":!0,"jon.":!0,"jr.":!0,"mr.":!0,"mrs.":!0,"ms.":!0,"messrs.":!0,
"mmes.":!0,"msgr.":!0,"prof.":!0,"rev.":!0,"rt.":!0,"sr.":!0,"st.":!0,"jan.":!0,"feb.":!0,"mar.":!0,"apr.":!0,"may.":!0,"jun.":!0,"jul.":!0,"aug.":!0,"spt.":!0,"oct.":!0,"nov.":!0,"dec.":!0,"co.":!0,"a.m.":!0,"p.m.":!0,"i.e.":!0,"no.":!0,"e.g.":!0,"etc.":!0},StopWords:{and:!0,to:!0,a:!0,of:!0,"for":!0,as:!0,i:!0,"with":!0,until:!0,is:!0,on:!0,that:!0,"this":!0,can:!0,"in":!0,be:!0,has:!0,"if":!0},HeadTags:{title:!0,script:!0,meta:!0,link:!0},ArticleNames:"article content container page main story".split(" "),
AttrTags:["id","class","itemprop","rel"],TitleTags:["Title","title"],AuthorTags:["[rel='author']","[itemprop='author']",".article-metabar-author",".asset-metabar-author"],TimeTags:["time:first",".date:first",".timestamp:first",".article-meta-date:first",".asset-metabar-time:first"],AuthorWildTags:"author_name author-name Author author Byline byline createdby".split(" "),TimeWildTags:"Time Date time date timestamp Timestamp Published published pub-date post-date posted Updated updated".split(" "),
MetaTimeTags:["meta[property='article:published_time']","meta[itemprop='datePublished']","meta[name='article:published_time']","meta[name='publishdate']"],BodyTags:"article entry body main content post container story page entry text".split(" "),CommonNodeNames:["div","span"],SpecialNodeNames:"article section time dd h1 h2 h3".split(" "),ScribdHost:"scribd.com",RsaPublicKey:"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6/cFc8xp/shUJy131ml\nI2URZT82B5wpjj2CESHqCMUujASIyNwNJ1AJuJ54SGidxMMoWh3q0u+6apKEDKDA\nUAEIMDlbKvtKDLpv+gKeGxSwb+16pEawaRkFca1RuP4zCsRJJnKXZwHg9mFz/jxW\nPznsmPMJ30Blc0ie40pA1VJm9qGcaUjDQrFwSUqyapoXpOOdO7cQXj3cYwS+ovsz\nkz7g1NfrgKapp81MJnO/gzEmfJenOxokUmDmzaegcTej4Ymd/MIyR0BjCakWlZbl\nm6lXIj1JBDPploKIC0rrX7O8ROeTJuJb/eQpZGKJIZdxHM23lZnkIYisD9EKLdw6\n8QIDAQAB\n-----END PUBLIC KEY-----"},
ErrorCode={None:0,NoTemplate:1,NoText:2,NoDocument:3,ParseArticleError:4,SystemError:500,ErrorMissingAPIKey:8001,ErrorInvalidAPIKey:8002,ErrorMissingAPIUser:8003,ErrorLicenseTokenRequired:8004,ErrorLicenseExpired:8005,ErrorLicenseNone:8006,ErrorLicenseTokenExpired:8007},ReadTypes={Selection:0,Paragraph:1,Article:2},ShortcutCommands={Read:"read",Stop:"Stop"},TranslationPopupKey={None:"None",Ctrl:"Ctrl",Alt:"Alt",Shift:"Shift"},ThemeBackgroundColors={"black-tie":"#ffeb80",blitzer:"#fbf8ee",cupertino:"#ffef8f",
"dark-hive":"#eeeeee","dot-luv":"#0b58a2",eggplant:"#fafafa","excite-bike":"#c5ddfc",flick:"#ffffff","hot-sneaks":"#ffff38",humanity:"#f5f5b5","le-frog":"#fbf5d0","mint-choc":"#619226",overcast:"#eeeeee","pepper-grinder":"#f7f3de",redmond:"#fbec88",smoothness:"#fbf9ee","south-street":"#fcf0ba",start:"#f8da4e",sunny:"#fff9e5","swanky-purse":"#d5ac5d",trontastic:"#f1fbe5","ui-darkness":"#eeeeee","ui-lightness":"#ffe45c",vader:"#555555"};function Langs$(){}
Langs$.prototype=function(){var b=[],f={ab:{name:"Abkhazian","native":"\u0430\u04a7\u0441\u0448\u04d9\u0430"},aa:{name:"Afar","native":"Afaraf"},af:{name:"Afrikaans","native":"Afrikaans"},ak:{name:"Akan","native":"Akan"},sq:{name:"Albanian","native":"Shqip"},am:{name:"Amharic","native":"\u12a0\u121b\u122d\u129b"},ar:{name:"Arabic","native":"\u0627\u0644\u0639\u0631\u0628\u064a\u0629"},an:{name:"Aragonese","native":"aragon\u00e9s"},hy:{name:"Armenian","native":"\u0540\u0561\u0575\u0565\u0580\u0565\u0576"},as:{name:"Assamese",
"native":"\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be"},av:{name:"Avaric","native":"\u0430\u0432\u0430\u0440 \u043c\u0430\u0446\u04c0"},ae:{name:"Avestan","native":"avesta"},ay:{name:"Aymara","native":"aymar aru"},az:{name:"Azerbaijani","native":"az\u0259rbaycan dili"},bm:{name:"Bambara","native":"bamanankan"},ba:{name:"Bashkir","native":"\u0431\u0430\u0448\u04a1\u043e\u0440\u0442"},eu:{name:"Basque","native":"euskara"},be:{name:"Belarusian","native":"\u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f \u043c\u043e\u0432\u0430"},
bn:{name:"Bengali","native":"\u09ac\u09be\u0982\u09b2\u09be"},bh:{name:"Bihari languages","native":"\u092d\u094b\u091c\u092a\u0941\u0930\u0940"},bi:{name:"Bislama","native":"Bislama"},bs:{name:"Bosnian","native":"bosanski jezik"},br:{name:"Breton","native":"brezhoneg"},bg:{name:"Bulgarian","native":"\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a"},my:{name:"Burmese","native":"\u1017\u1019\u102c\u1005\u102c"},ca:{name:"Catalan, Valencian","native":"catal\u00e0"},ch:{name:"Chamorro",
"native":"Chamoru"},ce:{name:"Chechen","native":"\u043d\u043e\u0445\u0447\u0438\u0439\u043d \u043c\u043e\u0442\u0442"},ny:{name:"Chichewa, Chewa, Nyanja","native":"chiChe\u0175a"},zh:{name:"Chinese","native":"\u4e2d\u6587"},cv:{name:"Chuvash","native":"\u0447\u04d1\u0432\u0430\u0448 \u0447\u04d7\u043b\u0445\u0438"},kw:{name:"Cornish","native":"Kernewek"},co:{name:"Corsican","native":"corsu"},cr:{name:"Cree","native":"\u14c0\u1426\u1403\u152d\u140d\u140f\u1423"},hr:{name:"Croatian","native":"hrvatski jezik"},
cs:{name:"Czech","native":"\u010de\u0161tina"},da:{name:"Danish","native":"dansk"},dv:{name:"Divehi, Dhivehi, Maldivian","native":"\u078b\u07a8\u0788\u07ac\u0780\u07a8"},nl:{name:"Dutch, Flemish","native":"Nederlands"},dz:{name:"Dzongkha","native":"\u0f62\u0fab\u0f7c\u0f44\u0f0b\u0f41"},en:{name:"English","native":"English"},eo:{name:"Esperanto","native":"Esperanto"},et:{name:"Estonian","native":"eesti"},ee:{name:"Ewe","native":"E\u028begbe"},fo:{name:"Faroese","native":"f\u00f8royskt"},fj:{name:"Fijian",
"native":"vosa Vakaviti"},fi:{name:"Finnish","native":"suomi"},fr:{name:"French","native":"fran\u00e7ais"},ff:{name:"Fulah","native":"Fulfulde"},gl:{name:"Galician","native":"galego"},ka:{name:"Georgian","native":"\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8"},de:{name:"German","native":"Deutsch"},el:{name:"Greek\u00a0(modern)","native":"\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"},gn:{name:"Guaran\u00ed","native":"Ava\u00f1e'\u1ebd"},gu:{name:"Gujarati","native":"\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0"},
ht:{name:"Haitian, Haitian Creole","native":"Krey\u00f2l ayisyen"},ha:{name:"Hausa","native":"\u0647\u064e\u0648\u064f\u0633\u064e"},he:{name:"Hebrew\u00a0(modern)","native":"\u05e2\u05d1\u05e8\u05d9\u05ea"},hz:{name:"Herero","native":"Otjiherero"},hi:{name:"Hindi","native":"\u0939\u093f\u0928\u094d\u0926\u0940"},ho:{name:"Hiri Motu","native":"Hiri Motu"},hu:{name:"Hungarian","native":"magyar"},ia:{name:"Interlingua","native":"Interlingua"},id:{name:"Indonesian","native":"Bahasa Indonesia"},ie:{name:"Interlingue",
"native":"Interlingue"},ga:{name:"Irish","native":"Gaeilge"},ig:{name:"Igbo","native":"As\u1ee5s\u1ee5 Igbo"},ik:{name:"Inupiaq","native":"I\u00f1upiaq"},io:{name:"Ido","native":"Ido"},is:{name:"Icelandic","native":"\u00cdslenska"},it:{name:"Italian","native":"italiano"},iu:{name:"Inuktitut","native":"\u1403\u14c4\u1483\u144e\u1450\u1466"},ja:{name:"Japanese","native":"\u65e5\u672c\u8a9e"},jv:{name:"Javanese","native":"basa Jawa"},kl:{name:"Kalaallisut, Greenlandic","native":"kalaallisut"},kn:{name:"Kannada",
"native":"\u0c95\u0ca8\u0ccd\u0ca8\u0ca1"},kr:{name:"Kanuri","native":"Kanuri"},ks:{name:"Kashmiri","native":"\u0915\u0936\u094d\u092e\u0940\u0930\u0940"},kk:{name:"Kazakh","native":"\u049b\u0430\u0437\u0430\u049b \u0442\u0456\u043b\u0456"},km:{name:"Central Khmer","native":"\u1781\u17d2\u1798\u17c2\u179a"},ki:{name:"Kikuyu, Gikuyu","native":"G\u0129k\u0169y\u0169"},rw:{name:"Kinyarwanda","native":"Ikinyarwanda"},ky:{name:"Kirghiz, Kyrgyz","native":"\u041a\u044b\u0440\u0433\u044b\u0437\u0447\u0430"},
kv:{name:"Komi","native":"\u043a\u043e\u043c\u0438 \u043a\u044b\u0432"},kg:{name:"Kongo","native":"Kikongo"},ko:{name:"Korean","native":"\ud55c\uad6d\uc5b4"},ku:{name:"Kurdish","native":"Kurd\u00ee"},kj:{name:"Kuanyama, Kwanyama","native":"Kuanyama"},la:{name:"Latin","native":"latine"},lb:{name:"Luxembourgish, Letzeburgesch","native":"L\u00ebtzebuergesch"},lg:{name:"Ganda","native":"Luganda"},li:{name:"Limburgan, Limburger, Limburgish","native":"Limburgs"},ln:{name:"Lingala","native":"Ling\u00e1la"},
lo:{name:"Lao","native":"\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7"},lt:{name:"Lithuanian","native":"lietuvi\u0173 kalba"},lu:{name:"Luba-Katanga","native":"Tshiluba"},lv:{name:"Latvian","native":"latvie\u0161u valoda"},gv:{name:"Manx","native":"Gaelg"},mk:{name:"Macedonian","native":"\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a"},mg:{name:"Malagasy","native":"fiteny malagasy"},ms:{name:"Malay","native":"bahasa Melayu"},ml:{name:"Malayalam","native":"\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02"},
mt:{name:"Maltese","native":"Malti"},mi:{name:"Maori","native":"te reo M\u0101ori"},mr:{name:"Marathi","native":"\u092e\u0930\u093e\u0920\u0940"},mh:{name:"Marshallese","native":"Kajin M\u0327aje\u013c"},mn:{name:"Mongolian","native":"\u041c\u043e\u043d\u0433\u043e\u043b \u0445\u044d\u043b"},na:{name:"Nauru","native":"Ekakair\u0169 Naoero"},nv:{name:"Navajo, Navaho","native":"Din\u00e9 bizaad"},nd:{name:"North Ndebele","native":"isi Ndebele"},ne:{name:"Nepali","native":"\u0928\u0947\u092a\u093e\u0932\u0940"},
ng:{name:"Ndonga","native":"Owambo"},nb:{name:"Norwegian Bokm\u00e5l","native":"Norsk bokm\u00e5l"},nn:{name:"Norwegian Nynorsk","native":"Norsk nynorsk"},no:{name:"Norwegian","native":"Norsk"},ii:{name:"Sichuan Yi, Nuosu","native":"\ua188\ua320\ua4bf Nuosuhxop"},nr:{name:"South Ndebele","native":"isi Ndebele"},oc:{name:"Occitan","native":"occitan"},oj:{name:"Ojibwa","native":"\u140a\u14c2\u1511\u14c8\u142f\u14a7\u140e\u14d0"},cu:{name:"Church\u00a0Slavic, Church\u00a0Slavonic,\u00a0Old\u00a0Church\u00a0Slavonic, Old\u00a0Slavonic,\u00a0Old\u00a0Bulgarian",
"native":"\u0469\u0437\u044b\u043a\u044a \u0441\u043b\u043e\u0432\u0463\u043d\u044c\u0441\u043a\u044a"},om:{name:"Oromo","native":"Afaan Oromoo"},or:{name:"Oriya","native":"\u0b13\u0b21\u0b3c\u0b3f\u0b06"},os:{name:"Ossetian, Ossetic","native":"\u0438\u0440\u043e\u043d \u00e6\u0432\u0437\u0430\u0433"},pa:{name:"Panjabi, Punjabi","native":"\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40"},pi:{name:"Pali","native":"\u092a\u093e\u0934\u093f"},fa:{name:"Persian","native":"\u0641\u0627\u0631\u0633\u06cc"},pl:{name:"Polish",
"native":"j\u0119zyk polski"},ps:{name:"Pashto, Pushto","native":"\u067e\u069a\u062a\u0648"},pt:{name:"Portuguese","native":"portugu\u00eas"},qu:{name:"Quechua","native":"Runa Simi"},rm:{name:"Romansh","native":"rumantsch grischun"},rn:{name:"Rundi","native":"Ikirundi"},ro:{name:"Romanian, Moldavian, Moldovan","native":"limba rom\u00e2n\u0103"},ru:{name:"Russian","native":"\u0420\u0443\u0441\u0441\u043a\u0438\u0439"},sa:{name:"Sanskrit","native":"\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d"},
sc:{name:"Sardinian","native":"sardu"},sd:{name:"Sindhi","native":"\u0938\u093f\u0928\u094d\u0927\u0940"},se:{name:"Northern Sami","native":"Davvis\u00e1megiella"},sm:{name:"Samoan","native":"gagana fa'a Samoa"},sg:{name:"Sango","native":"y\u00e2ng\u00e2 t\u00ee s\u00e4ng\u00f6"},sr:{name:"Serbian","native":"\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a"},gd:{name:"Gaelic, Scottish Gaelic","native":"G\u00e0idhlig"},sn:{name:"Shona","native":"chiShona"},si:{name:"Sinhala, Sinhalese",
"native":"\u0dc3\u0dd2\u0d82\u0dc4\u0dbd"},sk:{name:"Slovak","native":"sloven\u010dina"},sl:{name:"Slovenian","native":"sloven\u0161\u010dina"},so:{name:"Somali","native":"Soomaaliga"},st:{name:"Southern Sotho","native":"Sesotho"},es:{name:"Spanish, Castilian","native":"espa\u00f1ol"},su:{name:"Sundanese","native":"Basa Sunda"},sw:{name:"Swahili","native":"Kiswahili"},ss:{name:"Swati","native":"SiSwati"},sv:{name:"Swedish","native":"svenska"},ta:{name:"Tamil","native":"\u0ba4\u0bae\u0bbf\u0bb4\u0bcd"},
te:{name:"Telugu","native":"\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41"},tg:{name:"Tajik","native":"\u0442\u043e\u04b7\u0438\u043a\u04e3"},th:{name:"Thai","native":"\u0e44\u0e17\u0e22"},ti:{name:"Tigrinya","native":"\u1275\u130d\u122d\u129b"},bo:{name:"Tibetan","native":"\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42"},tk:{name:"Turkmen","native":"T\u00fcrkmen"},tl:{name:"Tagalog","native":"Wikang Tagalog"},tn:{name:"Tswana","native":"Setswana"},to:{name:"Tonga\u00a0(Tonga Islands)","native":"faka Tonga"},
tr:{name:"Turkish","native":"T\u00fcrk\u00e7e"},ts:{name:"Tsonga","native":"Xitsonga"},tt:{name:"Tatar","native":"\u0442\u0430\u0442\u0430\u0440 \u0442\u0435\u043b\u0435"},tw:{name:"Twi","native":"Twi"},ty:{name:"Tahitian","native":"Reo Tahiti"},ug:{name:"Uighur, Uyghur","native":"\u0626\u06c7\u064a\u063a\u06c7\u0631\u0686\u06d5"},uk:{name:"Ukrainian","native":"\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430 \u043c\u043e\u0432\u0430"},ur:{name:"Urdu","native":"\u0627\u0631\u062f\u0648"},
uz:{name:"Uzbek","native":"O\u02bbzbek"},ve:{name:"Venda","native":"Tshiven\u1e13a"},vi:{name:"Vietnamese","native":"Ti\u1ebfng Vi\u1ec7t"},vo:{name:"Volap\u00fck","native":"Volap\u00fck"},wa:{name:"Walloon","native":"walon"},cy:{name:"Welsh","native":"Cymraeg"},wo:{name:"Wolof","native":"Wollof"},fy:{name:"Western Frisian","native":"Frysk"},xh:{name:"Xhosa","native":"isiXhosa"},yi:{name:"Yiddish","native":"\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9"},yo:{name:"Yoruba","native":"Yor\u00f9b\u00e1"},za:{name:"Zhuang, Chuang",
"native":"Sa\u026f cue\u014b\u0185"},zu:{name:"Zulu","native":"isiZulu"}},e=function(a){a=f[a];return null==a?"":a.native},h=function(a){return f[a]},n=function(a,b){if(null==a)return null;a=a[b];return null==a?null:a.message},p=function(a,l){"zh"==a&&(a="zh_CN");var e=b[a];if(null!=e)return l(e);var d=a.split("-")[0];e=b[d];if(null!=e)return l(e);e=chrome.extension.getURL("_locales/"+a+"/messages.json");Utils.UrlGet(e,null,function(e,f){if(e&&null!=f)return b[a]=f,b[d]=f,l(f);e=chrome.extension.getURL("_locales/"+
d+"/messages.json");Utils.UrlGet(e,null,function(e,f){return e&&null!=f?(b[a]=f,b[d]=f,l(f)):l(null)})})};return{constructor:Langs$,GetNativeName:function(){return e.apply(this,arguments)},GetLanguage:function(){return h.apply(this,arguments)},GetLocale:function(){return p.apply(this,arguments)},GetLocaleMessage:function(){return n.apply(this,arguments)}}}();var Langs=new Langs$;String.isNullOrEmpty||(String.isNullOrEmpty=function(b){return null==b||""==b});String.prototype.in=String.prototype.in||function(){return 0<=arguments.indexOf(this)};Date.prototype.isValid=Date.prototype.isValid||function(){return!isNaN(this.getTime())};Array.prototype.last=Array.prototype.last||function(){return 0<this.length?this[this.length-1]:null};Array.prototype.first=Array.prototype.first||function(){return 0<this.length?this[0]:null};
$.extend($.expr[":"],{"node-names":function(b,f,e){return 0<=e[3].toLowerCase().split(",").indexOf(b.nodeName.toLowerCase())},startsWith:function(b,f,e){b=(b.innerText||"").trim().replace(/[\s]/g," ");return null!=b&&""!=b&&b.startsWith(e[3])},prefixes:function(b,f,e){b=(b.innerText||"").trim().replace(/[\s]/g," ");if(""!=b){prefixes=e[3]||"";e=[];if(prefixes.startsWith("'"))for(f=/'([^']*)'/g;match=f.exec(prefixes);)e.push(match[1]);else e.push(prefixes);f=0;for(var h=e.length;f<h;f++)if(b.startsWith(e[f]))return!0}return!1},
"has-text":function(b,f,e){if(0<=e[3].toLowerCase().split(",").indexOf(b.nodeName.toLowerCase()))for(f=0,e=b.childNodes.length;f<e;++f){var h=b.childNodes[f];if(3==h.nodeType&&/\S/.test(h.nodeValue))return!0}return!1}});function Utils$(){}
Utils$.prototype=function(){var b=function(c){console.log.apply(this,arguments)},f=function(c){console.warn.apply(this,arguments)},e=function(c){console.error.apply(this,arguments)},h=function(){return window.navigator.userLanguage||window.navigator.language},n=function(c,g,a){null!=c&&0!=c&&clearTimeout(c);return setTimeout(a,g)},p=function(c){clearTimeout(c);return null},a=function(c){var g=1<arguments.length?Array.prototype.slice.call(arguments,1):[];return chrome.i18n.getMessage.apply(this,[c,
g])},l=function(c,g){"string"==typeof c&&(null==g&&(g=c),c=$(c));null==g&&(g=c.prop("id"));if(!String.isNullOrEmpty(g)){g.startsWith("#")&&(g=g.substring(1,g.legnth));var a=Array.prototype.slice.call(arguments,1);a[0]=g;a=chrome.i18n.getMessage.apply(this,a);c.text(a)}},t=function(c){var g=null;c=c.match(/.+?:\/\/(.+?)\//);null!=c&&1<c.length&&(g=c[1].toLowerCase(),c=g.substring(0,4),"www."==c||"ww2."==c)&&(g=g.substring(4,g.length));return g},d=function(){return chrome.extension.getBackgroundPage().Background},
x=function(c){null==c&&(c=0);return parseInt(Date.now()/1E3)+c},u=function(c){return null==c?"":(new Date(c)).toJSON().split("T")[0]},v=function(c){if(null==c||null!=c.isValiad&&!c.isValid())return"";c=(new Date(c)).toJSON();c=c.split(".")[0];return c.split("T").join(" ")},A=function(c){return null==c?null:JSON.stringify(c,null,2)},w=function(c,g){if(String.isNullOrEmpty(c))return null;try{return JSON.parse(c)}catch(r){if(g)return null;throw r;}},B=function(c,g,b,k,d){d=d||function(){};return $.ajax(g,
{timeout:12E4,type:c,headers:b,data:k,success:function(c,g,a){d(!0,c,a)},error:function(c,b,r){String.isNullOrEmpty(r)&&(r=b);0==c.status&&null!=r&&"error"==r.toLowerCase()&&(r=a("error_connection_refused",t(g)));d(!1,r,c)}})},y=function(c,g,b,k,d){d=d||function(){};return $.ajax(g,{timeout:12E4,type:c,dataType:"json",headers:b,data:A(k),success:function(c,g,a){d(!0,c,a)},error:function(c,b,r){String.isNullOrEmpty(r)&&(r=b);0==c.status&&null!=r&&"error"==r.toLowerCase()&&(r=a("error_connection_refused",
t(g)));d(!1,r,c)}})},G=function(c,g,a){return B("GET",c,g,null,a)},z=function(c,g,a){return y("GET",c,g,null,a)},F=function(c,g,a,b){return y("POST",c,g,a,b)},H=function(c,g,a,b){return y("PUT",c,g,a,b)},q=function(c,g){"string"==typeof c&&(c=$(c));c.toggle(g)},k=function(c,g){"string"==typeof c&&(c=$(c));c.toggleClass("ui-state-disabled",!g)},C=function(c){"string"==typeof c&&(c=$(c));return c.is(":checked")},R=function(c,g){"string"==typeof c&&(c=$(c));c.prop("checked",g)},S=function(c,g){"string"==
typeof c&&(c=$(c));c.toggleClass("ui-state-disabled",g)},T=function(c,g,b){c=c.replace(/\n/g,"<br/>");c=String.isNullOrEmpty(b)?"<p>"+c+"</p>":"<table cellpadding='4'><tr><td valign='top'><span class='ui-icon "+b+"'/></td><td>"+c+"</td></tr></table>";g=$.extend({modal:!0,title:a("extName"),maxHeight:525,maxWidth:500,width:450,buttons:{Ok:function(){$(this).dialog("close")}}},g);$(c).dialog(g)},U=function(c,g,b){c="<p>"+c+"</p>";var r={};r[a("label_confirm")]=function(){$(this).dialog("close");b(!0)};
r[a("label_cancel")]=function(){$(this).dialog("close");b(!1)};g=$.extend({modal:!0,title:a("extName"),maxHeight:525,maxWidth:500,width:450,buttons:r},g);$(c).dialog(g)},V=function(c,g,b){c="<div><p>"+c+'</p><input type="text" class="ui-width-100" value="'+g+'"/></div>';g={};g[a("label_ok")]=function(){$(this).dialog("close");b(!0,$(this).find("input").val())};g[a("label_cancel")]=function(){$(this).dialog("close");b(!1,"")};var r=$.extend({modal:!0,title:a("extName"),maxHeight:525,maxWidth:500,width:450,
buttons:g,open:function(){$(this).find("input").select()}},r);$(c).dialog(r)},M=function(c,g,a){a=a||document;a=a.createElement(c);if(null!=g)for(c in g)a[c]=g[c];return a},I=function(c,g,a,b){g=M(g,a,b);c.appendChild(g);return g},N=function(c,g,a){g=g||document;var b=g.getElementsByTagName("head")[0];I(b,"link",{type:"text/css",rel:"stylesheet",href:c,onload:a},g)},W=function(c,g,a){g=g||document;var b=g.getElementsByTagName("head")[0];I(b,"script",{type:"text/javascript",onload:a,src:c},g)},X=function(c,
g,a){N("../lib/jquery-ui/themes/"+c+"/jquery-ui.css",g,a)},Y=function(c,g,a,b){c.append($("<option>",{value:g,text:a,title:b||a}))},Z=function(c,g){g=$("<textarea>").text(g).appendTo(c.parent()).focus().select();document.execCommand("copy");g.remove();c.focus()},aa=function(c){chrome.tabs.create({url:c},function(c){})},ba=function(c,g){var a=function(c){var a=c.id;0>a&&(a=0);g(c,a,t(c.url),c.url)};if(null!=c)return a(c);chrome.tabs.getSelected(a)},J=function(c){0<c.length&&c[0].scrollIntoViewIfNeeded()},
ca=function(c,a){var g=[];if(null!=c){c=c.split(a);for(var b=0,k=c.length;b<k;b++){var d=c[b];b<k-1&&(d+=a);g.push(d)}}return g},da=function(c,a){var g=[];$.each(c.split("\n"),function(c,b){g.push(O(b,a))});return g},P=function(c,a){for(var g=0,b=0,k=a.length;0<=(b=c.indexOf(a,b));)g++,b+=k;return g},D=function(c,a,b){b=b||-1;$.each(a,function(a,g){a=c.lastIndexOf(g);0<=a&&(a+=g.length,a>b&&(b=a))});return b},Q=function(c,a,b){b=b||-1;$.each(a,function(a,g){a=c.lastIndexOf(g);0<a&&a>b&&(b=a)});return b},
ea=function(c,a,b,k){var g=c.length;if(0>a||a>=g)return"";for(var d=a;0<=d&&d<g&&k(c[d]);)d+=b?-1:1;return 0>d?b?c.substring(0,a+1):c.substring(a):b?c.substring(d+1,a+1):c.substring(a,d)},fa=function(c,a){a=a||-1;for(var b=c.lastIndexOf(". ");b>a;){var g=ea(c,b,!0,function(c){return"."==c||"a"<=c&&"z">=c||"A"<=c&&"Z">=c});g=g.toLowerCase().trim();if("."==g||!Consts.AbbrWords[g])return b+1;b=c.lastIndexOf(". ",b-1)}return a},O=function(c,a){c=c.replace(/\n/g," ").replace(/\r/g," ");for(var b=[],g=
new RegExp("^.{1,"+a+"}\\b"),d=function(){var b=c.match(g);b=null==b||0==b.length?c.substring(0,a):b[0].trimEnd();var d=D(b,['."',"\u3002\u201d","\u3002","\uff1f"],-1);d=D(b,['."','".',"? "],d);d=fa(b,d);if(0<d||0<(d=D(b,["; "]))||0<(d=D(b,[", ","\uff0c"])))return d;d=D(b,"\u201d\uff09\uff3d\uff5d\u3001\uff1a".split(""),d);d=D(b,'.";" ;) ;] ;} ;: '.split(";"),d);d=Q(b,["\u201c","\uff08","\uff3b","\uff5b "],d);d=Q(b,[" ("," ["," {"],d);if(0<d)return d;var k=b.length;for(d=b.lastIndexOf(" ",k-1);0<
d;){k=b.substring(d+1,k).trim();if(""!=k&&Consts.StopWords[k])return d+1;k=d;d=b.lastIndexOf(" ",k-1)}return b.length};c.length>a;){var k=d();0>=k&&(k=a);b.push(c.substring(0,k));c=c.substring(k)}""!=c&&b.push(c);return b},E=function(c,a){for(var b=c.length;0<b;){var g=c.lastIndexOf('"',b);b=c.lastIndexOf(a,b);if(b>g)return b;b=c.lastIndexOf('"',g-1)-1}return-1},ha=function(c){var a,b=c.length;if(0<(a=E(c,"\u201c")))return c.substring(0,a);if(0<(a=E(c,"\u201d")))return c.substring(0,a+1);if(0<(a=
E(c,"; "))||0<(a=E(c,", "))||0<(a=E(c,": ")))return c.substring(0,a+2);a=c.lastIndexOf('"');if(0<a)return 0==P(c,'"')%2&&(a+=1),a<b&&"."==c[a]&&(a+=1),c.substring(0,a);if(0<(a=E(c,Consts.TtsIdPrefix)))return a=c.indexOf(Consts.TtsIdSurfix,a),c.substring(0,a+1);for(;0<b;){start=c.lastIndexOf(" ",b-1);0>start&&(start=0);a=c.substring(start+1,b);if(""!=a&&Consts.StopWords[a])return c.substring(0,start+1);b=start}return c},K=function(c,a){var b=function(c){a({selection:Langs.GetLocaleMessage(c,"text_voice_template_selection"),
paragraph:Langs.GetLocaleMessage(c,"text_voice_template_paragraph"),article:Langs.GetLocaleMessage(c,"text_voice_template_article")})};Langs.GetLocale(c,function(c){return null!=c?b(c):Langs.GetLocale("en",b)})},ia=function(c,a){var b=function(c){a({title:Langs.GetLocaleMessage(c,"text_voice_exmaple_title"),author:Langs.GetLocaleMessage(c,"text_voice_exmaple_author"),time:Langs.GetLocaleMessage(c,"text_voice_exmaple_time"),body:Langs.GetLocaleMessage(c,"text_voice_exmaple_body")})};Langs.GetLocale(c,
function(c){return null!=c?b(c):Langs.GetLocale("en",b)})},ja=function(c,a){var b="";String.isNullOrEmpty(c)||(b=c.split("-")[0]);String.isNullOrEmpty(b)&&(b="en");c=Settings.Data.VoiceTemplates[b];if(null!=c&&null!=c.templates)return a(c.templates);K(b,function(c){if(null!=c)return a(c);c=Settings.Data.VoiceTemplates[b];return null!=c&&null!=c.templates?a(c.templates):K("en",a)})},ka=function(c,a){c=c||{};return null==a?c.body:a.replace(/\{title\}/,c.title||"").replace(/\{author\}/,c.author||"").replace(/\{time\}/,
c.time||"").replace(/\{language\}/,Langs.GetNativeName(c.language||"")).replace(/\{body\}/,c.body||"")},la=function(c,a,b){L(c,MessageCommand.GetLanguage,null,null,function(g){g=String.isNullOrEmpty(g)?null:g.split("-")[0];if(""!=Langs.GetNativeName(g))return b(g);if(!a)return b(null);L(c,MessageCommand.GetTitle,null,null,function(c){c=(c||"").trim();if(String.isNullOrEmpty(c))return b(null);chrome.i18n.detectLanguage(c,function(c){return null!=c&&c.isReliable&&null!=c.languages&&0<c.languages.length&&
(c=c.languages[0],null!=c)?b(c.language.split("-")[0]):b(null)})})})},ma=function(c,a){chrome.identity.removeCachedAuthToken({token:c},function(){z(Config.RevokeUrl+c,null,function(c,b){return c?a(!0,"Token is revoked"):a(!1,"Failed to revoke token")})})},na=function(c,a){chrome.identity.getAuthToken({interactive:!0},function(b){if(chrome.runtime.lastError)return a(!1,chrome.runtime.lastError);z(c,{Authorization:"Bearer "+b},function(c,b,g){if(!c)return a(!1,b);if(null==b)return a(!1,"failed to get license server");
if(b.result&&"FULL"==b.accessLevel)a(!0,"FULL");else return b.result&&"FREE_TRIAL"==b.accessLevel?(Date.now()-parseInt(b.createdTime,10))/1E3/60/60/24<=Config.TrialDays?a(!0,"FREE_TRIAL"):a(!1,"Free trial ended already"):a(!1,"Please subscribe first")})})},L=function(c,a,b,d,k){chrome.tabs.sendMessage(c,{event:a,data:b},k)},oa=function(c){return Consts.TtsIdBuilder.replace("{0}",c)},pa=function(c){var a=[];c=c.replace(new RegExp(Consts.TtsIdRemover,"ig"),function(c,b,d,g){0>a.indexOf(b)&&a.push(b);
return""});return{text:c,ttsIds:a}},qa=function(c,a){if(null==c||""==c)return a;Array.isArray(c)?c.push(a):c=[c,a];return c},ra=function(c,a){null!=c&&""!=c&&(c=1==a?c.replace(/\s*\n+\s*/g,"\n").replace(/[ ]+/g," "):c.replace(/\s+/g," "),c=c.trim());return c},sa=function(c,a){String.isNullOrEmpty(c)||("string"==typeof a&&(a=[a]),$.each(a,function(a,b){b=b.toLowerCase();a=c.substring(0,Math.min(b.length+1,c.length)).toLowerCase();if(a==b+" "||a==b+":")c=c.substring(b.length+1,c.length)}));return c},
ta=function(c,a){a=a?new RegExp("^"+a+"+|"+a+"+$","g"):/^\s+|\s+$/g;return c.trim().replace(a,"").trim()},ua=function(c,a){a=a?new RegExp(a+"+$"):/\s+$/;return c.trim().replace(a,"").trim()},va=function(c,a){a=a?new RegExp("^"+a+"+"):/^\s+/;return c.trim().replace(a,"").trim()},wa=function(c){null!=c&&""!=c&&(c=c.toLowerCase().replace(/([^a-z])([a-z])(?=[a-z]{1})|^([a-z])/g,function(c,a,b,d){return"undefined"===typeof a?d.toUpperCase():a+b.toUpperCase()}));return c},xa=function(c,a){var b=new JSEncrypt;
b.setPublicKey(c);return b.encrypt(a)},ya=function(c,a,b){if(String.isNullOrEmpty(c))return"";for(var d=end="",k=-1,g=-1,q=0,e=a.length;q<e&&!(d=a[q],k=c.indexOf(d),0<=k);q++);if(""==d||0>k)return"";q=0;for(e=b.length;q<e&&!(end=b[q],g=c.lastIndexOf(end),0<=g);q++);return""==end||0>g?"":c.substring(k,g+end.length)},za=function(c,a,b){for(var d=0,k=a.length;d<k;d++){var g=c.indexOf(a[d],b);if(0<=g)return g}return-1},Aa=function(c,a,b,d){query=encodeURIComponent(c);z("https://www.google.com/async/dictw?async=term:"+
query+",corpus:"+b,null,function(c,a){var b={},k=null,g=null;c&&a&&2<=a.length&&(k=a[1])&&2<=k.length&&(g=k[1])&&(c=!1,g=g.replace(/src="/g,'_src="').replace(/srcset="/g,'_srcset="'),$(g).find(".lr_dct_ent>.vmod>.vmod").each(function(c,a){c=$(a);a=c.find("i:first").text();var d=b[a];null==d&&(b[a]=d=[]);c.find(">ol>li:lt(2)").each(function(c,a){c=$(a).find("div[data-dobid='dfn']>span:first").text();""!=c&&d.push(c)})}));var q="",e;for(e in b)c=b[e],q+="<div>"+e+"</div><ol>",$.each(c,function(){q+=
"<li>"+this+"</li>"}),q+="</ol></div>";d(""!=q,q)})},Ba=function(c,a,b,d){c=encodeURIComponent(c);z("https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl="+b+"&dt=bd&q="+c,null,function(c,a){var b=$("<div>");c&&a&&2<=a.length&&$.each(a[1],function(c,a){c=$("<div>").text(a[0]);var d=$("<ol>");a=$("<li>").text(a[1].join(", "));d.append(a).appendTo(c);b.append(c)});d(0<b.find("div").length,b.html())})},Ca=function(c,a,b,d){c=encodeURIComponent(c);z("https://"+b+".wikipedia.org/w/api.php?action=query&prop=extracts&titles="+
c+"&exintro=&exsentences=2&explaintext=&redirects=&formatversion=2&format=json",null,function(c,a){if(c&&a&&a.query&&a.query.pages&&(c=a.query.pages[0])&&!c.missing&&!c.invalid){var b=(c.extract||"").trim();if(""!=b)return d(!0,c.extract)}d(!1,b)})},Da=function(c,a,b,d){var k=[],g="";$.each(c.split("\n"),function(c,a){a=encodeURIComponent(a);6144<g.length+a.length?(k.push(g),g=a):(""!=g&&(g+=encodeURIComponent("\n")),g+=a)});""!=g&&k.push(g);c="";var q=function(a){if(a>=k.length)return d(!0,c);z("https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl="+
b+"&dt=t&q="+k[a],null,function(b,d){b&&0<d.length&&$.each(d[0],function(a,b){c+=b[0]});q(a+1)})};q(0)},Ea=function(a,b,d){var c=function(k){if(k>=a.length)return d(!0);b(k,a[k],function(a){if(a)return d(!1);c(k+1)})};c(0)},Fa=function(){return chrome.runtime.getManifest()},Ga=function(a,b){a=a||"";1024<a.length&&(a=a.substring(0,1024));chrome.i18n.detectLanguage(a,function(a){if(null!=a&&null!=a.languages&&0<a.languages.length){var c=a.languages[0];if(a.isReliable||85<=c.percentage)return b(c.language.split("-")[0])}return b(null)})},
Ha=function(a){return chrome.extension.getURL(a)},Ia=function(a,b){if(null==a||""==a)return"";a=a.match(b);return null!=a&&1<a.length?a[1]:""};return{LogInfo:function(){return b.apply(this,arguments)},LogWarn:function(){return f.apply(this,arguments)},LogError:function(){return e.apply(this,arguments)},GetUserLanguage:function(){return h.apply(this,arguments)},SetTimeout:function(){return n.apply(this,arguments)},ClearTimeout:function(){return p.apply(this,arguments)},GetMessage:function(){return a.apply(this,
arguments)},SetLocaleText:function(){return l.apply(this,arguments)},GetUrlHost:function(){return t.apply(this,arguments)},Background:function(){return d.apply(this,arguments)},NowInSeconds:function(){return x.apply(this,arguments)},GetDate:function(){return u.apply(this,arguments)},GetDateTime:function(){return v.apply(this,arguments)},ToJsonString:function(){return A.apply(this,arguments)},UrlRequest:function(){return y.apply(this,arguments)},UrlGetRaw:function(){return G.apply(this,arguments)},
UrlGet:function(){return z.apply(this,arguments)},UrlPost:function(){return F.apply(this,arguments)},UrlPut:function(){return H.apply(this,arguments)},ShowElement:function(){return q.apply(this,arguments)},EnableElement:function(){return k.apply(this,arguments)},IsChecked:function(){return C.apply(this,arguments)},CheckButton:function(){return R.apply(this,arguments)},DisableBox:function(){return S.apply(this,arguments)},MessageBox:function(){return T.apply(this,arguments)},Confirm:function(){return U.apply(this,
arguments)},Prompt:function(){return V.apply(this,arguments)},CreateElement:function(){return M.apply(this,arguments)},AppendChild:function(){return I.apply(this,arguments)},AppendStyleUrl:function(){return N.apply(this,arguments)},AppendScriptUrl:function(){return W.apply(this,arguments)},ApplyTheme:function(){return X.apply(this,arguments)},AppendSelectOption:function(){return Y.apply(this,arguments)},CopyToClipboard:function(){return Z.apply(this,arguments)},OpenNewTab:function(){return aa.apply(this,
arguments)},GetTabInfo:function(){return ba.apply(this,arguments)},ScrollIntoView:function(){return J.apply(this,arguments)},BreakTextToBlocks:function(){return da.apply(this,arguments)},GetSubStrCount:function(){return P.apply(this,arguments)},BreakLineToBlocks:function(){return O.apply(this,arguments)},BreakTextByQuoatAndWord:function(){return ha.apply(this,arguments)},GetVoiceTemplateFromLocale:function(){return K.apply(this,arguments)},GetArticleExampleFromLocale:function(){return ia.apply(this,
arguments)},GetVoiceTemplateByLanguage:function(){return ja.apply(this,arguments)},GetArticleTextByTemplate:function(){return ka.apply(this,arguments)},GetTabLanguage:function(){return la.apply(this,arguments)},RevokeToken:function(){return ma.apply(this,arguments)},CheckLicense:function(){return na.apply(this,arguments)},SendMessage:function(){return L.apply(this,arguments)},BuildTtsId:function(){return oa.apply(this,arguments)},AddToArray:function(){return qa.apply(this,arguments)},ReduceWhitespaces:function(){return ra.apply(this,
arguments)},RemovePrefix:function(){return sa.apply(this,arguments)},Trim:function(){return ta.apply(this,arguments)},TrimLeft:function(){return va.apply(this,arguments)},TrimRight:function(){return ua.apply(this,arguments)},ToUpperCaseFirstLetters:function(){return wa.apply(this,arguments)},RsaEncryption:function(){return xa.apply(this,arguments)},ParseJson:function(){return w.apply(this,arguments)},SubstrByTags:function(){return ya.apply(this,arguments)},IndexOfAny:function(){return za.apply(this,
arguments)},Translate:function(){return Da.apply(this,arguments)},GetManifest:function(){return Fa.apply(this,arguments)},SplitTextToItems:function(){return ca.apply(this,arguments)},DetectLanguage:function(){return Ga.apply(this,arguments)},RemoveTtsIds:function(){return pa.apply(this,arguments)},GetWiki:function(){return Ca.apply(this,arguments)},GetDict:function(){return Ba.apply(this,arguments)},GetDefine:function(){return Aa.apply(this,arguments)},EachAsync:function(){return Ea.apply(this,arguments)},
ExtGetUrl:function(){return Ha.apply(this,arguments)},GetFirstMatch:function(){return Ia.apply(this,arguments)},constructor:Utils$}}();var Utils=new Utils$;function Db$(){}
Db$.prototype=function(){var b=function(a,b){var d="site:"+a.toLowerCase();chrome.storage.local.get(d,function(a){try{var e=a[d];if(null!=e&&""!=e)return b(JSON.parse(e))}catch(w){Utils.LogError("Failed to parse json: "+w)}return b(null)})},f=function(a,b,e){a="site:"+a.toLowerCase();var d={};d[a]=JSON.stringify(b);chrome.storage.local.set(d,e)},e=function(a,b){a="site:"+a.toLowerCase();chrome.storage.local.remove(a,b)},h=function(a){chrome.storage.local.get(null,function(b){var d=[];$.each(Object.keys(b),
function(a,e){if(e.startsWith("book:"))try{d.push(JSON.parse(b[e]))}catch(w){}});a(d)})},n=function(a,b){var d="book:"+a.toLowerCase();chrome.storage.local.get(d,function(a){try{var e=JSON.parse(a[d]);return b(e)}catch(w){}return b(null)})},p=function(a,b,e){a="book:"+a.toLowerCase();var d={};d[a]=JSON.stringify(b);chrome.storage.local.set(d,e)},a=function(a,b){a="book:"+a.toLowerCase();chrome.storage.local.remove(a,b)},l=function(a){chrome.storage.local.get("settings:",function(b){a(b["settings:"])})},
t=function(a,b){var d={};d["settings:"]=a;chrome.storage.local.set(d,b)};return{constructor:Db$,GetSite:function(){return b.apply(this,arguments)},SaveSite:function(){return f.apply(this,arguments)},RemoveSite:function(){return e.apply(this,arguments)},GetBooks:function(){return h.apply(this,arguments)},GetBook:function(){return n.apply(this,arguments)},SaveBook:function(){return p.apply(this,arguments)},RemoveBook:function(){return a.apply(this,arguments)},GetSettings:function(){return l.apply(this,
arguments)},SaveSettings:function(){return t.apply(this,arguments)}}}();var Db=new Db$;function Repo$(){}
Repo$.prototype=function(){var b=function(a,b,e){Db.GetSite(a,function(d){if(null!=d){var l=Utils.NowInSeconds()-d.cachedTime;if(0<=l&&l<=Consts.SiteExpireInSeconds)return e(ErrorCode.None,d)}if(b)return e(ErrorCode.None,null);l=null==d?null:d.lastModified;if(null!=d&&0<d.id&&0==d.official)return Service.GetSiteById(d.id,l,function(b,l,f){p(b,a,d,l,f,e)});Service.GetPrimarySite(a,l,function(b,l,f){p(b,a,d,l,f,e)})})},f=function(a,b){null==a.createdTime&&(a.cachedTime=a.createdTime=Utils.NowInSeconds());
a.updatedTime=Utils.NowInSeconds();Db.SaveSite(a.host,a,b)},e=function(a,b){Db.RemoveSite(a,b)},h=function(a){Db.GetSettings(a)},n=function(a,b){null!=a&&Db.SaveSettings(a,b)},p=function(a,b,e,d,p,h){if(a!=ErrorCode.None)return h(a,d);switch(p.status){case 200:a=d.template;if(String.isNullOrEmpty(a))return h(ErrorCode.None,null);try{d.template=JSON.parse(a)}catch(v){return Utils.LogError("Invalid site template, Host:'${site.host}', Id:'${site.id}', temmplate:'${site.template}'"),h(ErrorCode.None,
null)}d.lastModified=parseInt(p.getResponseHeader("Last-Modified"));d.cachedTime=Utils.NowInSeconds();d.verified=!0;d.published=!0;d.visible=null!=e?e.visible:!1;f(d);return h(ErrorCode.None,d);case 304:return e.cachedTime=Utils.NowInSeconds(),f(e),h(ErrorCode.None,e);case 404:return null!=e?(e.cachedTime=Utils.NowInSeconds(),f(e),h(ErrorCode.None,e)):h(ErrorCode.NoTemplate,Utils.GetMessage("error_article_no_template",b));default:return h(ErrorCode.SystemError,d)}};return{GetSite:function(){return b.apply(this,
arguments)},SaveSite:function(){return f.apply(this,arguments)},RemoveSite:function(){return e.apply(this,arguments)},GetSettings:function(){return h.apply(this,arguments)},SaveSettings:function(){return n.apply(this,arguments)},constructor:Repo$}}();var Repo=new Repo$;function Extractor$(){}
Extractor$.prototype=function(){var b=function(a,b,e){Utils.GetTabInfo(a,function(a,k,q,f){l(k,b,function(a){Utils.DetectLanguage(a,function(b){d(k,q,!0,function(d,k){if(d!=ErrorCode.None)return e(d,k);d={body:a,language:t(b,k),host:q};return e(ErrorCode.None,d)})})})})},f=function(a,b){Utils.GetTabInfo(a,function(a,k,e,q){Utils.SendMessage(k,MessageCommand.GetParagraph,null,null,function(a){var q=A(a);Utils.DetectLanguage(q,function(a){d(k,e,!0,function(d,k){if(d!=ErrorCode.None)return b(d,k);d=
{body:q,language:t(a,k),host:e};return b(ErrorCode.None,d)})})})})},e=function(a,b,d,e){Utils.GetTabInfo(a,function(a,k,q,f){Repo.GetSiteByHost(q,b,function(b,k){return b!=ErrorCode.None?e(b,k):n(a,k,d,e)})})},h=function(a,b,d){chrome.webNavigation.getAllFrames({tabId:a},function(a){var k=0;$.each(a,function(a,d){if(a==b)return k=d.frameId,!1});d(k)})},n=function(b,d,e,f){if("string"==typeof b)return H(b,d,f);Utils.GetTabInfo(b,function(b,k,q,l){x(k,d,function(b,d,l){if(b!=ErrorCode.None)return f(b,
d);if(null==d)return f(ErrorCode.None,d);var C=("string"==typeof d.article?d.article:d.article.select)||"";C.endsWith(":first")||(C+=":first");h(k,0,function(b){b=0;Utils.SendMessage(k,MessageCommand.GetDocument,{select:C,needTag:e},b,function(k){k=(k||"").trim();if(String.isNullOrEmpty(k))return f(ErrorCode.NoDocument,Utils.GetMessage("error_document_no_text"));try{var e=p(k),C=a(k),h=w(e,C,q,d);if(null==h)return f(ErrorCode.None,null);h.host=q;h.pageIdx=l;h.frameId=b;if("object"==typeof d.language&&
(0==d.language.auto||"false"==d.language.auto))return h.language=d.language.default,f(ErrorCode.None,h);Utils.DetectLanguage(h.body,function(a){h.language=t(a,d);f(ErrorCode.None,h)})}catch(J){return f(ErrorCode.ParseArticleError,Utils.GetMessage("error_parse_article",J.message))}})})})})},p=function(a){a=a.replace(/src=/gi,"_src=").replace(/srcset=/gi,"_srcset=").replace(/<html>/i,"<doc>").replace(/<html /i,"<doc ").replace(/<\/html>/i,"</doc>");a=$(a);a.find("style,iframe").remove();return a},a=
function(a){a=Utils.SubstrByTags(a,["<body>","<body ","<BODY>","<BODY "],["</body>","</BODY>"]);a=a.replace(/src=/gi,"_src=").replace(/srcset=/gi,"_srcset=").replace(/<body>/i,"<div>").replace(/<body /i,"<div ").replace(/<\/body>/i,"</div>");a=$(a);a.find("style,iframe").remove();return a},l=function(a,b,d){if(!String.isNullOrEmpty(b))return d(b);Utils.SendMessage(a,MessageCommand.GetSelection,null,null,d)},t=function(a,b){String.isNullOrEmpty(a)&&null!=b&&(a=b.language);return String.isNullOrEmpty(a)?
"en":a.split("-")[0]},d=function(a,b,d,e){Repo.GetSiteByHost(b,d,function(b,d){return b!=ErrorCode.None?e(b,d):x(a,d,e)})},x=function(a,b,d){if(null==b||null==b.template||0==b.template.length)return d(ErrorCode.None,null);var k=b.template.length;if(1==k)return d(ErrorCode.None,b.template[0]);var e=function(f){if(f>=k)return d(ErrorCode.None,b.template[k-1]);var l=b.template[f];u(a,l.match||("string"==typeof l.article?l.article:l.article.select),function(a){if(a)return d(ErrorCode.None,l,f);e(++f)})};
e(0)},u=function(a,b,d){if(null==b||"body"==b.toLowerCase())return d(!0);"string"==typeof b&&(b=[b]);var k=b.length,e=function(f){if(f>=k)return d(!1);Utils.SendMessage(a,MessageCommand.CheckArticle,b[f],null,function(a){if(a)return d(!0);e(f+1)})};e(0)},v=function(a){a.find("[tts-id]").each(function(){var a=$(this),b=a.attr("tts-id"),d=a.text().trim();null==b||String.isNullOrEmpty(d)||(a.prepend(Utils.BuildTtsId(b)),a.find("[tts-id]").removeAttr("tts-id"))})},A=function(a){a=$("<div>").append(a);
v(a);return Utils.ReduceWhitespaces(a.text(),!0)},w=function(a,b,d,e){var k={};b=B(a,b,e.article,!0);v(b);var f=F(a,b,e.title);String.isNullOrEmpty(f)&&(f=Utils.GetMessage("text_article_no_title"));k.title=f;"string"==typeof e.author&&(e.author={select:e.author});null==e.author.join&&(e.author.join=", ");f=F(a,b,e.author);f=String.isNullOrEmpty(f)?d:Utils.ToUpperCaseFirstLetters(f).replace(" And "," and ");f=Utils.RemovePrefix(f,["by","por"]);k.author=Utils.Trim(f,"[,|;|:|-]");f=F(a,b,e.time);String.isNullOrEmpty(f)&&
(f=Utils.GetMessage("text_article_no_date"));f=Utils.RemovePrefix(f,["published","updated","posted","on","at"]);f.substring(0,10);f=f.split("\n")[0].replace(/(\d+?)m/i,"$1 minute").replace(/$1 minutes/i,"1 minute").replace(/(\d+?)h/i,"$1 hours").replace(/$1 hours/i,"1 hour");d=/([^T]+T\d+:\d+:\d+)/.exec(f);null!=d&&1<d.length&&!String.isNullOrEmpty(d[1])&&(f=d[1].replace("T"," "),f.endsWith(" 00:00:00")&&(f=f.substring(0,f.length-9)));k.time=Utils.Trim(f,"[,|;|-|:]");b.find("script").remove();b=B(a,
b,e.body);1<b.length&&(b=$("<div>").append(b));1==b.length&&(b=$(b[0].outerHTML.replace(/\n/g," ")));b.find("p,div,h0,h1,h2,h3,h4,h5,h6,li").append("\n");b.find("br").replaceWith("\n");k.body=Utils.ReduceWhitespaces(b.text(),!0);return k},B=function(a,b,d,e){"string"==typeof d&&(d={select:d});if(null!=d["pre-remove"]||null!=d.remove)b=b.clone(),1<b.length&&(b=$("<div>").append(b));null!=d["pre-remove"]&&b.find(d["pre-remove"]).remove();if(1!=e&&null!=d.select){e=d.select;"string"==typeof e&&(e=[e]);
for(var f=b,k=0,l=e.length;k<l&&!(b=z(a,f,e[k]),0<b.length);k++);}a=d["filter-node-types"];if(null!=a){var p=a.split(",");b=b.contents().filter(function(a,b){return 0<=p.indexOf(b.nodeType.toString())})}null!=d.remove&&(1<b.length&&(b=$("<div/>").append(b)),b.find(d.remove).remove());return b.append(" ")},y=function(a,b){var d=null!=b.split;a=Utils.ReduceWhitespaces(a,d);if(null!=b.split){var e=b.split.lastIndexOf(":"),f=0>e?b.split:b.split.substring(0,e),k=0>e?"":b.split.substring(e+1).trim();k=
""==k?["0"]:k.split(",");var l=a.split(f);a=[];e=0;for(var p=k.length;e<p;e++){var h=parseInt(k[e]);0<=h&&h<l.length&&a.push(l[h])}a=a.join(f)}b=b.match;if(!String.isNullOrEmpty(a)&&null!=b)for("string"==typeof b&&(b=[b]),e=0,p=b.length;e<p;e++)if(f=(new RegExp(b[e],"i")).exec(a),null!=f&&1<f.length&&!String.isNullOrEmpty(f[1])){a=f[1];break}return Utils.ReduceWhitespaces(a,d)},G=function(a,b){a=String.isNullOrEmpty(b.attr)?a.text():a.attr(b.attr);if(!String.isNullOrEmpty(b.json)){a=a.replace(",]",
"]");var d=Utils.ParseJson(a);$.each(b.json.split("."),function(a,b){null!=d&&(d=d[b])});a=null==d?"":d.toString()}return a},z=function(a,b,d){var e=d.trim().toLowerCase();0<=e.indexOf("[")&&(e=e.split("[")[0]);0<=e.indexOf(":")&&(e=e.split(":")[0]);return 1==Consts.HeadTags[e]?a.find(d):b.find(d)},F=function(a,b,d,e){"string"==typeof d&&(d={select:d});if(String.isNullOrEmpty(d.select))return d.default||"";b=B(a,b,d);b.find("br").replaceWith("\n");"string"==typeof d.select&&d.select.toLowerCase().startsWith("meta[")&&
null==d.attr&&(d.attr="content");a="";if(String.isNullOrEmpty(d.join))a=G(b,d),a=y(a,d);else{var f=[];$.each(b,function(a,b){a=G($(b),d);a=y(a,d).trim();String.isNullOrEmpty(a)||f.push(a)});a=Utils.ReduceWhitespaces(f.join(d.join),!1)}a=(a||"").trim();String.isNullOrEmpty(a)&&(a=d.default||"");return a},H=function(b,d,e){var f=p(b);b=a(b);for(var l=null,k=0,h=d.template.length;k<h&&!(l=d.template[k],0<f.find(l.match||("string"==typeof l.article?l.article:l.article.select)).length);k++);d=w(f,b,d.host,
l);e(d)};return{constructor:Extractor$,GetSelection:function(){return b.apply(this,arguments)},GetParagraph:function(){return f.apply(this,arguments)},GetArticle:function(){return e.apply(this,arguments)},GetArticleBySite:function(){return n.apply(this,arguments)}}}();var Extractor=new Extractor$;function Tts$(){}
Tts$.prototype=function(){var b=null,f=0,e=null,h=function(a,b){var d="";$.each(a.blocks,function(a,b){if(255<=d.length)return!1;d+=" "+b.text});Utils.DetectLanguage(d,b)},n=function(a,b,d){Db.GetBook(a,function(e){null!=e&&(e.position=b,e.timestamp=(new Date).getTime(),Db.SaveBook(a,e,d))})},p=function(a,b){if(null!=a.voice&&"default"!=a.voice)return b(a.voice);var d=function(a){x(a,function(a){return b(a.voiceName)})};if(null!=a.language&&""!=a.language)return d(a.language);h(a,function(b){a.language=
b||"en";a.voice="default";Db.SaveBook(a.bookId,a);d(b)})},a=function(a){var b=[];$.each(Utils.BreakLineToBlocks(a.text,Settings.Data.maxBlockSize),function(a,d){b.push({text:d})});if(a.pageEnd&&0<b.length){var d=b.first(),e=b.last();null==a.partialPos?e.nextPageAtEnd=!0:(a=6E4*a.text.substring(0,a.partialPos).split(" ").length/240/Settings.Data.ttsRate,d.nextPageAtStart=!0,d.nextPageDelay=a,e.nextPageCheck=!0)}return b},l=function(a,b){d();Utils.DetectLanguage(b,function(a){x("en",function(a){chrome.tts.speak(b,
{volume:Settings.Data.ttsVolume,rate:Settings.Data.ttsRate,voiceName:a.voiceName})})})},t=function(d,l){Utils.GetTabInfo(d,function(d,h,t,k){f=h;b=l.bookId;p(l,function(b){$.each(l.blocks,function(d,k){d<l.start||$.each(a(k),function(a,d){chrome.tts.speak(d.text,{enqueue:!0,volume:Settings.Data.ttsVolume,rate:Settings.Data.ttsRate,voiceName:b,onEvent:function(a){switch(a.type){case "start":Utils.SendMessage(f,MessageCommand.Highlight,{position:k.position,ttsHighlight:Settings.Data.ttsHighlight});
n(l.bookId,k.position);d.nextPageAtStart&&(e=Utils.SetTimeout(e,d.nextPageDelay,function(){e=null;A(!0)}));break;case "end":d.nextPageAtEnd&&A(!1),d.nextPageCheck&&e&&(e=Utils.ClearTimeout(e),A(!0))}}})})})})})},d=function(){e=Utils.ClearTimeout(e);null!=b&&(b=null,Utils.SendMessage(f,MessageCommand.UpdateReadingStatus,{isReading:!1}));chrome.tts.stop()},x=function(a,b){String.isNullOrEmpty(a)&&(a="en");var d=a.split("-")[0],e=Settings.Data.VoiceTemplates[d];null==e&&(e=new VoiceTemplate(d),e.template=
Settings.Data.VoiceTemplates.en.template);v(function(d){d=d[a]||d.en;for(var f=e.voice,l=0,p=d.length;l<p;l++){var h=d[l];if(h.voiceName==f)return b(h)}return 0<d.length?b(d[0]):b({voiceName:"native"})})},u=function(a){chrome.tts.getVoices(a)},v=function(a){u(function(b){var d=[];$.each(b,function(){if(!String.isNullOrEmpty(this.lang)){var a=this.lang.split("-")[0],b=d[a];null==b&&(b=d[a]=[]);b.push(this)}});b=d.en;for(var e=0,f=b.length;e<f;e++){var l=b[e];if("Google US English"==l.voiceName){b.splice(e,
1);b.splice(0,0,l);break}}a(d)})},A=function(a){Utils.SendMessage(f,MessageCommand.NextPage,{resumeWhenBookReady:!0,skipFirstBlock:a})},w=function(a){chrome.tts.isSpeaking(a)},B=function(){return b},y=function(a){};return{Play:function(){return Play.apply(this,arguments)},Pause:function(){return Pause.apply(this,arguments)},Resume:function(){return Resume.apply(this,arguments)},Stop:function(){return d.apply(this,arguments)},ReadBook:function(){return t.apply(this,arguments)},GetVoices:function(){return u.apply(this,
arguments)},GetVoiceGroups:function(){return v.apply(this,arguments)},IsReading:function(){return w.apply(this,arguments)},GetReadingBookId:function(){return B.apply(this,arguments)},RegisterEvent:function(){return y.apply(this,arguments)},Speak:function(){return l.apply(this,arguments)},constructor:Tts$}}();var Tts=new Tts$;function Feedback$(){}
Feedback$.prototype=function(){var b=function(b,h){Repo.GetSite(b,!0,function(b,e){if(b==ErrorCode.None&&null!=e&&null!=e.id&&0!=e.id){var a=f(h);Service.PutSiteIssues(e.id,a,function(b,f){b==ErrorCode.None&&(b=!1,e.issues!=a&&(e.issues=a,b=!0),0!=a&&(e.cachedTime=0,b=!0),b&&Repo.SaveSite(e))})}})},f=function(b){var e=IssueType.None;if(null==b)e+=IssueType.Missing;else if(null==b.blocks||0==b.blocks.length)e+=IssueType.Body;return e};return{constructor:Feedback$,PutBookIssues:function(){return b.apply(this,arguments)}}}();
var Feedback=new Feedback$;function BookData(){this.bookId="";this.position=0;this.cover="";this.timestamp=0}function SiteTemplate(){this.id=0;this.host="";this.template=[new PageTemplate];this.createdTime;this.updatedTime;this.cachedTime;this.lastModified;this.official=this.published=this.verified=!1;this.issues=-1;this.visible=!1}function ArticleData(){this.language="en";this.host;this.title;this.author;this.time;this.body}function PageLanuageData(){this.default="en";this.auto=!1}
function PageTemplate(){this.example="";this.language="en";this.article="body";this.title="title";this.author=".author:first";this.time="time:first";this.body={"pre-remove":"figure,aside,header,footer",select:"p",remove:"div"}}
function SettingsData(){this.activeLanguageCode=this.activeTab="";this.theme=this.username=this.userGuid=null;this.maxBlockSize=150;this.ttsRate=this.ttsVolume=1;this.ttsRateGap=.25;this.ttsScroll=this.ttsHighlight=!0;this.VoiceTemplates={};this.translationLanguage="en";this.translationPopupEnabled=!0;this.translationPopupKey=TranslationPopupKey.None}function VoiceTemplate(b){this.code=void 0===b?"en":b;this.voice="default";this.example=this.template=null}
function TemplateData(){this.attr=this.match=this.remove=this.select=this.default=""};var Config={ConfigUrl:"https://sites.google.com/site/ireadwebpage/config.json",UserApiKey:"E38FC4F8-0B6F-4B4B-B378-8A760A648131",LicenseUrl:"https://www.googleapis.com/chromewebstore/v1.1/userlicenses/",RevokeUrl:"https://accounts.google.com/o/oauth2/revoke?token=",AppStoreUrl:"https://chrome.google.com/webstore/detail/tts-scribd-reader/lnaecppekphilbjkgfgbjhjiokkpfgeh",DefaultServiceUrl:"http://ec2-35-165-140-185.us-west-2.compute.amazonaws.com/v1/"};function Service$(){}
Service$.prototype=function(){var b=null,f=function(a,b,e){a="sites/"+a;var f=d();f["If-Modified-Since"]=b;u("GET",a,f,null,e)},e=function(a,b,e){var f=d();f["If-Modified-Since"]=b;u("GET","sites/host/"+a+"/primary",f,null,e)},h=function(a,b){var e=d();return u("GET","sites/host/"+a,e,null,b)},n=function(a,b,e){var f=d();b={template:JSON.stringify(b)};u("PUT","sites/host/"+a+"/template",f,b,e)},p=function(a,b,e){var f=d();u("PUT","sites/"+a+"/issues/"+b,f,null,e)},a=function(a,b,e){var f=d();a="users/guid/"+
t()+"?name="+encodeURIComponent(a)+"&email="+encodeURIComponent(b);u("PUT",a,f,null,e)},l=function(a,b){var e=d();u("POST","issues",e,a,b)},t=function(){Settings.ResetData();return Settings.Data.userGuid},d=function(){var a=Config.UserApiKey,d=t();null==b&&(b=Utils.GetManifest().version);return{"X-API-KEY":a,"X-API-USER":d,"X-APP-VER":b}},x=function(a,b,d){if(!a)return d(ErrorCode.None,null);chrome.identity.getAuthToken({interactive:!1},function(a){return chrome.runtime.lastError?d(ErrorCode.SystemError,
chrome.runtime.lastError.message):b?chrome.identity.removeCachedAuthToken({token:a},function(){chrome.identity.getAuthToken({interactive:!1},function(a){return chrome.runtime.lastError?d(ErrorCode.SystemError,chrome.runtime.lastError.message):d(ErrorCode.None,a)})}):d(ErrorCode.None,a)})},u=function(a,b,d,e,f,l,h){x(void 0===l?!1:l,void 0===h?!1:h,function(l,h){if(l!=ErrorCode.None)return f(l,h);d=d||{};null!=h&&(d.Authorization=Utils.RsaEncryption(Consts.RsaPublicKey,"Bearer "+h));v(a,b,d,e,function(l,
h,p){if(l!=ErrorCode.None)return f(l,h);if(200==p.status||304==p.status||404==p.status)return f(ErrorCode.None,h,p);if(401!=p.status)return f(ErrorCode.SystemError,h,p);l=JSON.parse(p.responseText);return l.code==ErrorCode.ErrorLicenseTokenRequired?u(a,b,d,e,f,!0,!1):l.code==ErrorCode.ErrorLicenseTokenExpired?u(a,b,d,e,f,!0,!0):f(l.code,l.message)})})},v=function(a,b,d,e,f){Utils.Background().SettingsGetServiceUrl(!1,function(l,h){if(l!=ErrorCode.None)return f(l,h);url=h+b;Utils.UrlRequest(a,url,
d,e,function(e,l,h){if(0!=h.status&&503!=h.status)return f(ErrorCode.None,l,h);Utils.Background().SettingsGetServiceUrl(!0,function(e,h){if(e!=ErrorCode.None)return f(e,h);url=h+b;Utils.UrlRequest(a,url,d,l,function(a,b,d){return f(ErrorCode.None,b,d)})})})})};return{constructor:Service$,GetSiteById:function(){return f.apply(this,arguments)},GetPrimarySite:function(){return e.apply(this,arguments)},GetSitesByHost:function(){return h.apply(this,arguments)},PutSiteTemplate:function(){return n.apply(this,
arguments)},PutSiteIssues:function(){return p.apply(this,arguments)},UpdateUserInfo:function(){return a.apply(this,arguments)},SubmitIssue:function(){return l.apply(this,arguments)}}}();var Service=new Service$;function Settings$(){}
Settings$.prototype=function(){var b=null,f=function(){var f=!1,a=Utils.Background().SettingsGetData();String.isNullOrEmpty(a.theme)&&(a.theme="cupertino",f=!0);null==a.voice&&(a.voice="native",f=!0);null==a.activeTab&&(a.activeTab=0,f=!0);null==a.maxBlockSize&&(a.maxBlockSize=120,f=!0);null==a.ttsVolume&&(a.ttsVolume=1,f=!0);null==a.ttsRate&&(a.ttsRate=1,f=!0);null==a.ttsRateGap&&(a.ttsRateGap=.25,f=!0);null==a.ttsHighlight&&(f=a.ttsHighlight=!0);null==a.ttsScroll&&(f=a.ttsScroll=!0);null==a.VoiceTemplates&&
(a.VoiceTemplates=[],f=!0);null==a.VoiceTemplates.en&&(a.VoiceTemplates.en=new VoiceTemplate("en"),f=!0);String.isNullOrEmpty(a.translationLanguage)&&(a.translationLanguage=(window.navigator.language||"").split("-")[0],f=!0);null==a.translationPopupEnabled&&(a.translationPopupEnabled=!0,a.translationPopupKey=TranslationPopupKey.None,f=!0);null==a.krBoxPos&&(a.krBoxPos={top:"60px"},f=!0);f&&e();b=a;n()},e=function(){Utils.Background().SettingsSaveData()},h=function(f){if(f&&f.id&&""!=f.id)return f.extensionId=
Config.AppStoreUrl.split("/").last(),f=JSON.stringify(f),b.userGuid="sru"+(new Hashes.SHA1).hex(f),e();f=(b.userGuid||"").trim();if(""==f||"null"==f||"undefined"==f)return f=new Uint32Array(4),window.crypto.getRandomValues(f),f=JSON.stringify(f),b.userGuid="srg"+(new Hashes.SHA1).hex(f),e()},n=function(){chrome.identity.getProfileUserInfo(h);chrome.identity.onSignInChanged.addListener(function(b,a){chrome.identity.getProfileUserInfo(h)})};return{constructor:Settings$,Data:null,Init:function(){f.apply(this,
arguments);this.Data=b},Save:function(){return e.apply(this,arguments)},ResetData:function(){return h.apply(this,arguments)}}}();var Settings=new Settings$;$(function(){Settings.Init();Popup.Run()});$.widget("custom.selectmenu_theme",$.ui.selectmenu,{_renderItem:function(b,f){var e=$("<li>",{value:f.value});f=$("<div>",{align:"center"}).append($("<img/>",{src:"../lib/jquery-ui/gallery/theme_90_"+f.value+".png"})).append($("<div>",{text:f.label}));return e.append(f).appendTo(b)}});function DialogBookSettings$(){}
DialogBookSettings$.prototype=function(){var b=null,f=null,e=function(a,e){b=a;Tts.GetVoiceGroups(function(a){f=a;$("#dlg_book_settings").dialog({width:550,modal:!0,buttons:{Close:function(){$(this).dialog("close")}},open:h,close:function(a,b){}})})},h=function(a,e){$(this).find("#edt_book_bookId").text(b.bookId);$(this).find("#edt_book_title").text(b.title);$(this).find("#edt_book_authors").text(b.authors);var d=$("#lst_book_lang").html(""),l;for(l in f)a=Langs.GetLanguage(l),null!=a&&Utils.AppendSelectOption(d,
l,a.native,a.name);a=b.language||"en";d.val(a).selectmenu({width:120,change:n});d=$("#lst_book_voice").html("");Utils.AppendSelectOption(d,"default","Default");$.each(f[a],function(){Utils.AppendSelectOption(d,this.voiceName,this.voiceName)});d.val(b.voice||"default").selectmenu({width:300,change:p});d.selectmenu("refresh")},n=function(b,e){b=$("#lst_book_lang").val();var d=$("#lst_book_voice").html("");Utils.AppendSelectOption(d,"default","Default");$.each(f[b],function(){Utils.AppendSelectOption(d,
this.voiceName,this.voiceName)});d.val("default").selectmenu("destroy").selectmenu({width:300,change:p});d.selectmenu("refresh");a()},p=function(b,e){a()},a=function(){b.language=$("#lst_book_lang").val();b.voice=$("#lst_book_voice").val();Db.SaveBook(b.bookId,b);Utils.GetTabInfo(null,function(a,b,d,e){Utils.SendMessage(b,MessageCommand.Read)})};return{constructor:DialogBookSettings$,Run:function(){return e.apply(this,arguments)}}}();var DialogBookSettings=new DialogBookSettings$;
function PopupSettingsVoices$(){}
PopupSettingsVoices$.prototype=function(){var b=!1,f=function(a){Tts.GetVoiceGroups(function(a){$("#dlg_settings_voices").dialog({modal:!0,maxHeight:500,maxWidth:500,width:520,title:Utils.GetMessage("label_tts_modify_voice_templates"),open:function(b,d){e(a)},close:function(){b&&(Tts.Stop(),b=!1)},buttons:{"Test Voice":p,Close:function(){$(this).dialog("close")}}})})},e=function(a){h(a);$("#list-settings-voices-languages").change(function(){n(a)});$("#list-settings-voices-prefer").change(function(){var a=$("#list-settings-voices-languages").val(),
b=$("#list-settings-voices-prefer").val();Settings.Data.VoiceTemplates[a].voice=b;Settings.Save()})},h=function(a){var b=$("#list-settings-voices-languages").html("");for(d in a){var e=Langs.GetLanguage(d);null!=e&&Utils.AppendSelectOption(b,d,e.native,e.name)}var d=Settings.Data.activeLanguageCode;String.isNullOrEmpty(d)&&(d=b.find("option:first").val());b.val(d);n(a)},n=function(a){var b=$("#list-settings-voices-languages").val();$("#lab_voices_language_code").text(b);$list=$("#list-settings-voices-prefer").html("");
Utils.AppendSelectOption($list,"default","Default");$.each(a[b],function(){Utils.AppendSelectOption($list,this.voiceName,this.voiceName)});a=Settings.Data.VoiceTemplates[b];null==a&&(a=Settings.Data.VoiceTemplates[b]=new VoiceTemplate,a.code=b);$list.val(a.voice);if($list.val()!=a.voice){var e=$list.find("option:first").val();$list.val(e)}e=function(a){$("#edit-settings-voices-template-selection").val(a.selection);$("#edit-settings-voices-template-paragraph").val(a.paragraph);$("#edit-settings-voices-template-article").val(a.article)};
null!=a.templates?e(a.templates):Utils.GetVoiceTemplateFromLocale(b,e);e=function(a){$("#edit-settings-voices-title").val(a.title);$("#edit-settings-voices-author").val(a.author);$("#edit-settings-voices-time").val(a.time);$("#edit-settings-voices-body").val(a.body)};null!=a.example?e(a.example):Utils.GetArticleExampleFromLocale(b,e);Settings.Data.activeLanguageCode=b;Settings.Save()},p=function(){var a=$("#edt_settings_voices_sample").val(),e=$("#list-settings-voices-prefer").val();"default"==e&&
(e=$("#list-settings-voices-prefer").find("option:eq(1)").val());Tts.Stop();$.each(Utils.BreakLineToBlocks(a,Settings.Data.maxBlockSize),function(a,b){chrome.tts.speak(b,{enqueue:!0,volume:Settings.Data.ttsVolume,rate:Settings.Data.ttsRate,voiceName:e})});b=!0};return{constructor:PopupSettingsVoices$,Run:function(){return f.apply(this,arguments)}}}();var PopupSettingsVoices=new PopupSettingsVoices$;function PopupSettings$(){}
PopupSettings$.prototype=function(){var b=!1,f=function(){1!=b&&(b=!0,e())},e=function(){$("#list_settings_themes").val(Settings.Data.theme).selectmenu_theme({width:150,change:function(a,b){n(a,b)},open:function(a,b){a=$(this).val();a=$(this).selectmenu_theme("menuWidget").find("[value='"+a+"']");0<a.length&&a[0].scrollIntoView()}});$("#edit_settings_username").val(Settings.Data.username).change(function(){return p()});$("#edit_settings_useremail").val(Settings.Data.useremail).change(function(){return p()});
$("#btn_settings_tts_templates").click(function(a){PopupSettingsVoices.Run(null)});$("#lab_settings_tts_volume").text(Math.floor(100*Settings.Data.ttsVolume));$("#bar_settings_tts_volume").slider({value:100*Settings.Data.ttsVolume,min:0,max:100,slide:function(a,b){$("#lab_settings_tts_volume").text(Math.floor(b.value))},change:function(a,b){Settings.Data.ttsVolume=b.value/100;Settings.Save();Utils.GetTabInfo(null,function(a,b,e,f){Utils.SendMessage(b,MessageCommand.Read)})}});$("#lab_settings_tts_rate").text(Settings.Data.ttsRate+
"x");$("#bar_settings_tts_rate").slider({value:100*Settings.Data.ttsRate,min:50,max:200,slide:function(a,b){$("#lab_settings_tts_rate").text(b.value/100+"x")},change:function(a,b){Settings.Data.ttsRate=b.value/100;Settings.Save();Utils.GetTabInfo(null,function(a,b,e,f){Utils.SendMessage(b,MessageCommand.Read)})}});$("#edit_settings_tts_max_length").val(Settings.Data.maxBlockSize).change(function(a){Settings.Data.maxBlockSize=$(this).val();Settings.Save()});h();Utils.CheckButton("#btn_settings_tts_highlight",
Settings.Data.ttsHighlight);$("#btn_settings_tts_highlight").change(function(a){Settings.Data.ttsHighlight=Utils.IsChecked("#btn_settings_tts_highlight");Settings.Save();Utils.GetTabInfo(null,function(a,b,d,e){Utils.SendMessage(b,MessageCommand.Highlight,{ttsHighlight:Settings.Data.ttsHighlight})})});Utils.CheckButton("#edit_settings_popup_enable",Settings.Data.translationPopupEnabled);$("#edit_settings_popup_enable").change(function(a){Settings.Data.translationPopupEnabled=Utils.IsChecked("#edit_settings_popup_enable");
Settings.Save()});$("#list_settings_translation_key").val(Settings.Data.translationPopupKey).change(function(a){Settings.Data.translationPopupKey=$(this).val();Settings.Save()})},h=function(){Tts.GetVoiceGroups(function(a){var b=$("#list_settings_translation_languages"),e;for(e in a)a=Langs.GetNativeName(e),Utils.AppendSelectOption(b,e,a);b.val(Settings.Data.translationLanguage).selectmenu({change:function(a,b){Settings.Data.translationLanguage=b.item.value;Settings.Save();Utils.Background().UpdateTranslationMenus()}})})},
n=function(a,b){a=b.item.value;Settings.Data.theme=a;Settings.Save();Utils.ApplyTheme(a,null);Utils.GetTabInfo(null,function(a,b,e,f){Utils.SendMessage(b,MessageCommand.Style,{styleUrl:Utils.ExtGetUrl("lib/jquery-ui/themes/"+Settings.Data.theme+"/jquery-ui.css"),themeBackgroundColor:ThemeBackgroundColors[Settings.Data.theme]})})},p=function(){var a=$("#edit_settings_username").val(),b=$("#edit_settings_useremail").val();Settings.Data.username=a;Settings.Data.useremail=b;Settings.Save();Service.UpdateUserInfo(a,
b)};return{constructor:PopupSettings$,Activate:function(){return f.apply(this,arguments)}}}();var PopupSettings=new PopupSettings$;function DialogReportIssue$(){}
DialogReportIssue$.prototype=function(){var b=function(b){f();b={};b[Utils.GetMessage("label_submit")]=function(){n($(this))};b[Utils.GetMessage("label_close")]=function(){$(this).dialog("close")};$("#dlg-report-issue").dialog({modal:!0,maxHeight:525,maxWidth:500,width:560,title:Utils.GetMessage("label_report_an_issue"),open:function(a,b){e($(this))},buttons:b})},f=function(){Utils.GetTabInfo(null,function(b,a,e,f){$("#edit-issue-url").val(b.url)});Extractor.GetArticle(null,!0,!1,function(b,a){if(null==
a||null==a.article)Utils.CheckButton("#btn_issue_no_template",!0);else{b=String.isNullOrEmpty(a.article.title);var e=String.isNullOrEmpty(a.article.author),f=String.isNullOrEmpty(a.article.time);a=String.isNullOrEmpty(a.article.body);Utils.CheckButton("#btn_issue_wrong_template_title",b);Utils.CheckButton("#btn_issue_wrong_template_author",e);Utils.CheckButton("#btn_issue_wrong_template_time",f);Utils.CheckButton("#btn_issue_wrong_template_body",a);Utils.CheckButton(b||e||f||a?"#btn_issue_wrong_template":
"#btn_issue_other_issues",!0)}h()})},e=function(b){$("#btn_issue_no_template,#btn_issue_wrong_template").change(function(){h()});$("#edit-issue-note").focus()},h=function(){var b=Utils.IsChecked("#btn_issue_wrong_template");Utils.DisableBox("#box-issue-template-wrong",!b)},n=function(b){var a=$("#edit-issue-url").val(),e=Utils.GetUrlHost(a),f=$("#edit-issue-note").val()||"",d="",h=IssueType.None;if(Utils.IsChecked("#btn_issue_no_template"))d=Utils.GetMessage("report_issue_no_template",e,a,f),h+=IssueType.Missing;
else if(Utils.IsChecked("#btn_issue_wrong_template")){h+=IssueType.Wrong;var n=[];Utils.IsChecked("#btn_issue_wrong_template_title")&&(n.push(Utils.GetMessage("label_title")),h+=IssueType.Title);Utils.IsChecked("#btn_issue_wrong_template_author")&&(n.push(Utils.GetMessage("label_author")),h+=IssueType.Author);Utils.IsChecked("#btn_issue_wrong_template_time")&&(n.push(Utils.GetMessage("label_time")),h+=IssueType.Time);Utils.IsChecked("#btn_issue_wrong_template_body")&&(n.push(Utils.GetMessage("label_body")),
h+=IssueType.Body);Utils.IsChecked("#btn_issue_wrong_template_language")&&(n.push(Utils.GetMessage("label_language")),h+=IssueType.Language);d=Utils.GetMessage("report_issue_wrong_template",e,n.join(", "),a,f)}else Utils.IsChecked("#btn_issue_other_issues")&&(h+=IssueType.Others,d=Utils.GetMessage("report_issue_other_issues",e,a,f));Repo.GetSiteByHost(e,!0,function(e,l){e=e==ErrorCode.None?l:null;Service.SubmitIssue({siteId:null==e?0:e.id,url:a,note:f,issues:h},function(a,e){Utils.IsChecked("#btn_issue_enable_feedback")&&
(Utils.CopyToClipboard(b,d),Utils.OpenNewTab(Config.AppStoreUrl+"/support"))})})};return{constructor:DialogReportIssue$,Run:function(){return b.apply(this,arguments)}}}();var DialogReportIssue=new DialogReportIssue$;function PopupIssues$(){}PopupIssues$.prototype=function(){var b=!1,f=function(){1!=b&&(b=!0,Init())};return{constructor:PopupIssues$,Activate:function(){return f.apply(this,arguments)}}}();var PopupIssues=new PopupIssues$;function PopupNews$(){}
PopupNews$.prototype=function(){var b=!1,f=function(){1!=b&&(b=!0,h())},e=function(){var b=$(this).text();chrome.tabs.update({url:b})},h=function(){Utils.UrlGetRaw("https://github.com/ttsreadit/tts_scribd_reader/wiki/release_notes",null,function(b,e){b&&null!=e&&""!=e&&($news=$(e).find("div.markdown-body"),$news.find("svg").remove(),$news.find("img").addClass("news_img"),$news.find("a[name*='user-content-']").each(function(){var a=$(this).attr("name").replace("user-content-","");$(this).attr("name",
a)}),$("#tabs_news").append($news))});$("#news_foreign_site_url").click(e)};return{constructor:PopupNews$,Activate:function(){return f.apply(this,arguments)}}}();var PopupNews=new PopupNews$;function PopupAbout$(){}
PopupAbout$.prototype=function(){var b=!1,f=function(){1!=b&&(b=!0,e())},e=function(){var b=Utils.GetManifest();$("#lab_product").text(b.name+" "+b.version);$("#btn_feedback").click(function(){chrome.tabs.create({url:Config.AppStoreUrl+"/support"})});$("#btn_userinfo").click(function(){$('<p style="word-wrap: break-word">UserID: '+Settings.Data.userGuid+"</p>").dialog({title:"User Info",modal:!0,width:400,buttons:{Ok:function(){$(this).dialog("close")}}})});$("#img_logo").click(function(){Repo.RemoveSite(Consts.ScribdHost)})};
return{constructor:PopupAbout$,Activate:function(){return f.apply(this,arguments)}}}();var PopupAbout=new PopupAbout$;function PopupBooks$(){}
PopupBooks$.prototype=function(){var b=!1,f=function(){1!=b&&(b=!0,$("#tab_books_list").disableSelection(),h())},e=function(a){Tts.Stop();a=$(this).parents("li").attr("bookId");Db.GetBook(a,function(a){Utils.GetTabInfo(null,function(b,e){Utils.Background().SendPendingCommand(e,MessageCommand.Read,{force:!0});chrome.tabs.update({url:a.url});window.close()})})},h=function(){var b=$("#tab_books_list").html("");Db.GetBooks(function(f){f.sort(function(a,b){return b.timestamp-a.timestamp});$.each(f,function(a,
d){var f=null==d.title||""==d.title?"&nbsp;":d.title,h=null==d.authors||""==d.authors?"&nbsp;":d.authors;a=$("<img>").addClass("cover").attr("title","Click to read\n"+d.title+"\nby "+d.authors+"'..").attr("src",d.cover).click(e);f=$("<div>").addClass("title").attr("title",d.title).text(f).click(e);h=$("<div>").addClass("authors").attr("title",d.authors).text(h).click(e);var l=$("<button>",{class:"remove button ui-corner-all",click:n}).append($("<i>",{class:"ui-icon ui-icon-trash"})),t=$("<button>",
{class:"setting button ui-corner-all",click:p}).append($("<i>",{class:"ui-icon ui-icon-gear"})),u=$("<button>",{class:"progress button ui-corner-all",text:d.progress||"0%"});l=$("<div>",{class:"buttons"}).append(u,l,t);$("<li>",{bookId:d.bookId}).append(l,a,f,h).appendTo(b)});f=$("<li>");var d=$("<span>",{class:"ui-icon ui-icon-home"}),h=$("<button>",{class:"site ui-corner-all",title:"Click to open Scribd library",click:a}),l=$("<div>",{class:"title",text:"Open Library..",click:a});f.append(h.append(d)).append(l).appendTo(b);
b.find("button").button()})},n=function(a){var b=$(this).parents("li"),d=b.attr("bookId");Db.RemoveBook(d);b.remove();a.preventDefault();return!1},p=function(a){a=$(this).parents("li").attr("bookId");Db.GetBook(a,function(a){DialogBookSettings.Run(a)})},a=function(a){Tts.Stop();Utils.GetTabInfo(null,function(a,b,e,f){Utils.Background().SendPendingCommand(b,MessageCommand.OpenLibrary);chrome.tabs.update({url:"https://www.scribd.com/books"});window.close()})};return{Activate:function(){return f.apply(this,
arguments)},constructor:PopupBooks$}}();var PopupBooks=new PopupBooks$;function PopupTutorial$(){}PopupTutorial$.prototype=function(){var b=!1,f=function(){1!=b&&(b=!0,$("#link_try_out_site").click(e),$("#tutorial_example_site_url").click(h))},e=function(){var b=$(this).prop("href");chrome.tabs.update({url:b})},h=function(){var b=$(this).text();chrome.tabs.update({url:b})};return{constructor:PopupTutorial$,Activate:function(){return f.apply(this,arguments)}}}();var PopupTutorial=new PopupTutorial$;
function Popup$(){}
Popup$.prototype=function(){var b=function(){Utils.ApplyTheme(Settings.Data.theme);$("button").button();e(Settings.Data.activeTab);$("#tabs").tabs({active:Settings.Data.activeTab,heightStyle:"fill",activate:function(b,f){Settings.Data.activeTab=$("#tabs").tabs("option","active");Settings.Save();e(Settings.Data.activeTab)}});f();Repo.GetSite(Consts.ScribdHost,!1,function(b,e){})},f=function(){$(".ui-locale-text").each(function(){var b=$(this),e=b.prop("id").replace(/-/g,"_");b.text(chrome.i18n.getMessage(e))});$(".ui-locale-title").each(function(){var b=
$(this),e=b.prop("id").replace(/-/g,"_")+"_title";b.prop("title",chrome.i18n.getMessage(e))})},e=function(b){switch(b){case 1:PopupSettings.Activate();break;case 2:PopupNews.Activate();break;case 3:PopupAbout.Activate();break;default:PopupBooks.Activate()}};return{constructor:Popup$,Run:function(){return b.apply(this,arguments)}}}();var Popup=new Popup$;
